### ISSUE TITLE
Complete loss of internet connectivity in Prism Launcher 7.1

### ISSUE THREAD

**Issue by sorket** [PrismLauncher/PrismLauncher#1248]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 7.1

### Version of Qt

Qt 6.5.1

### Description of bug

Opening the Prism Launcher, after doing a reinstall, after deleting the TLS folder and re-extracting it, Prism Launcher 7.1 still does not have any connectivity to the internet. I used to be able to resolve this by rebooting my machine, but now it isn't functional at all. I have tried the official Minecraft launcher and Minecraft plus all connectivity to its servers seem to be just fine. I have also tried accessing Prism Launcher specific URLs in my browser and they connect just fine. I cannot do anything that requires a connection in Prism Launcher, such as add a Microsoft account, or even see the news.

Here is a log file from Prism:
[PrismLauncher-0.log](https://github.com/PrismLauncher/PrismLauncher/files/11837432/PrismLauncher-0.log)

### Steps to reproduce

* Open Prism Launcher
* Notice that the news isn't loading
* Attempt to link a Microsoft account 
* It will be stuck on "Working..." indefinitely.

### Suspected cause

It is unknown to me what would be causing this. I've looked at other issues where the TLS folder was the problem ( #660 ), but that is not the case for me.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by biomseed** [comment]
It's the same for me. #1247

**Comment by biomseed** [comment]
It seems the problem has fixed itself. Open Prism Launcher again.

**Comment by ThatGuy6211** [comment]
I have been experiencing this all day. Still happening now. I notice if i go to the modpack browser and mod browsers, it only shows curseforge and no other platforms. I tried restarting the program as admin and was able to browse mods and modpacks, but when i launch my instance with normal launch (not offline or demo), it says i am still offline in game. If i try to update any mods with the "check for updates" function, it finds updates but hangs on downloading and installing them.

**Comment by NickTTD** [comment]
Can confirm exactly the same on my end, can't add accounts, no news, can't browse any of the mod pages (modrinth etc) not even curseforge, tried reinstalling using .exe and zipped versions + deleting %appdata% folder, I don't have any PrismLauncher folder on my ProgramFiles / ProgramFilesx86

**Comment by NickTTD** [comment]
If you guys want a workaround, I downloaded the 32bit portable version of the launcher, remember to always backup your instances folder.

**Comment by ThatGuy6211** [comment]
issue resolved itself for me upon logging into computer today

**Comment by biomseed** [comment]
> issue resolved itself for me upon logging into computer today

it un-solves itself, it happened to me #1247

**Comment by ghost** [comment]
It is internet service interruption causing this. Close Prism, disconnect from the internet then reconnect, and relaunch Prism, that solves it.

**Comment by biomseed** [comment]
> It is internet service interruption causing this. Close Prism, disconnect from the internet then reconnect, and relaunch Prism, that solves it.

wh

**Comment by ghost** [comment]
> > It is internet service interruption causing this. Close Prism, disconnect from the internet then reconnect, and relaunch Prism, that solves it.
> 
> wh

I know, right? But this happened to me a few times last week and this is how I fix it, none of the other suggested fixes work so I tried the simplest and oldest trick in the book, restart the internet connection. You don't have to turn off your router, just disconnect your device from the Wi-Fi or disable the Ethernet connection on the computer then reconnect.

**Comment by sorket** [comment]
This still happens for me, and "disconnecting and reconnecting" internet shouldn't make this "resolved". It's resolved when the underlying reason is found and patched. I don't want to have to disable my Ethernet connection and reconnect to be able to use Prism Launcher.

Hoping there's someone who's able to find the reason for this bug soon.

**Comment by falkreon** [comment]
This is still an issue. Resetting the network adapter does indeed fix the problem, but this can happen *in the middle of a session*, and still happens in 7.1.

**Comment by legobmw99** [comment]
This issue seems to be affecting me. I'm unable to play online, and the "Install Forge" button fails. 7.1 and 7.2

**Comment by biomseed** [comment]
> This issue seems to be affecting me. I'm unable to play online, and the "Install Forge" button fails. 7.1 and 7.2

turning wifi off and back on again doesn't fix things?

**Comment by legobmw99** [comment]
Does not seem to, that's also not a very workable long-term solution if it did

**Comment by kaiserjd** [comment]
I've been having a similar issue for the past few months, no amount of reinstalling or changing internet adapter settings has seemed to help. Issue was present in 7.1 and still appears to be in 7.2

Don't know if this will help, looks very similar to the one above: 
[PrismLauncher-0.log](https://github.com/PrismLauncher/PrismLauncher/files/12305545/PrismLauncher-0.log)

**Comment by sorket** [comment]
Just a question for everyone that is experiencing this issue- have you all ran a Windows 10 debloater or any "debloater" for Windows? I'm out of reasons why Prism Launcher is breaking and why my Java instances (both server and client) won't authenticate with Minecraft properly. The issue persists on both my debloated Windows server and my PC.

**Comment by falkreon** [comment]
> have you all ran a Windows 10 debloater or any "debloater" for Windows

I'm running linux, so it's not a Windows problem at all.

**Comment by Nathan22211** [comment]
similar issue on 7.2. Also it seems to prevent new instances from being run properly as I can't get 1.20.1 with forge to launch with the crash mentioning the launcher itself

`Exception caught from launcher
java.lang.ClassNotFoundException: io.github.zekerzhayard.forgewrapper.installer.Main
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.prismlauncher.utils.ReflectionUtils.findMainMethod(ReflectionUtils.java:151)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Exiting with ERROR
Process exited with code 2.`

**Comment by DraconicBlaze28** [comment]
I just started having this issue today. Version 7.2, on Windows 11. Disabling and enabling wifi doesn't seem to do anything either. Did anyone ever find a fix?

**Comment by biomseed** [comment]
> I just started having this issue today. Version 7.2, on Windows 11. Disabling and enabling wifi doesn't seem to do anything either. Did anyone ever find a fix?

nah

**Comment by D-Maxwell** [comment]
Toggling internet connectivity does not solve the issue. This shouldn't have much to do with missing services given that this is only an issue on an almost vanilla Windows 10 instance and not on my own which I have debloated to extreme lengths.

**Comment by falkreon** [comment]
> Toggling internet connectivity does not solve the issue. This shouldn't have much to do with missing services given that this is only an issue on an almost vanilla Windows 10 instance and not on my own which I have debloated to extreme lengths.

Again, this is present in a slim linux system too, so it's not a bloat issue.

**Comment by D-Maxwell** [comment]
It would seem that upon reinstalling the launcher --and having fully purged Prism user data, as well as previous MultiMC user data, which may or may not have had an effect-- as an AppXPackage instead of a traditional program install, followed by a mandatory reboot (for some reason), the modrinth integration worked once more.

You've got leads, please fix this issue.

**Comment by Deauthorized** [comment]
This is happening on fedora linux as well it seems

**Comment by khankul** [comment]
8.4 is still affected.
No network connectivity at all (no Prism updates, no news, no downloading instances, no logins, nothing), using both installer and portable versions. This issue plagues at least two separate Windows machines that I know, both of them have Prism's network requests (`launcher.task.net.download`) failing `with reason QNetworkReply::UnknownNetworkError` in the logs. Turning VPN and proxy settings on and off doesn't change a thing. I can fetch the resources that Prism is trying to access using a browser, and all Prism executables are whitelisted using Windows Firewall, so I have no reason to believe that there are any *network* issues.

In addition, a Linux machine in the same network as the Windows one runs Prism with no connectivity issues.

**Comment by Trial97** [comment]
@khankul can you try the nightly version:
Where can I download unstable builds of Prism Launcher?
You can download unstable builds [here](https://nightly.link/PrismLauncher/PrismLauncher/workflows/trigger_builds/develop).

:warning: Caution
>Unstable builds have more bugs and are therefore more likely to break! By using the latest commit you are using software which has not been properly tested. For this reason we recommend using Portable or AppImage builds, or least making a backup.

And if you are on windows try both mingw and mscv versions.
Also the nightly logs are a little more verbose regarding network errors.

**Comment by khankul** [comment]
@Trial97 I launched both MSVC and MinGW versions (portable), got met with error messages and then quit. Logs of both versions have identical errors in them. They look like this:
```
[launcher.task.net.download]: "{uuid}" Failed "https://prismlauncher.org/feed/feed.xml" with reason QNetworkReply::UnknownNetworkError
[launcher.task.net.download]: "{uuid}" HTTP Status 0 ;error "The credentials were not recognized / Invalid argument"
```
[mingw.log](https://github.com/user-attachments/files/16073145/mingw.log)
[msvc.log](https://github.com/user-attachments/files/16073146/msvc.log)

**Comment by Trial97** [comment]
This looks like an error that is generated by openssl.
Your openssl instalation may not be up to date.
Try installing the latest openssl version: https://stackoverflow.com/questions/51374639/is-there-an-openssl-for-windows
If that doesn't work try to fix windows certificates. Here are some sites that I found with posible solutions:
- https://www.wikihow.com/Fix-SSL-Certificate-Errors-on-PC-or-Mac
- from https://help.gamemaker.io/hc/en-us/articles/9455965321501-Windows-7-users-may-need-to-install-an-Windows-Update-package-to-fix-certificate-issues I got https://support.microsoft.com/en-us/topic/support-for-urgent-trusted-root-updates-for-windows-root-certificate-program-in-windows-a4ac4d6c-7c62-3b6e-dfd2-377982bf3ea5

And most of them suggest the system clock so also check that

**Comment by khankul** [comment]
> Your openssl instalation may not be up to date.

I don't think Windows even has such a thing as a system-wide OpenSSL installation. Accordingly, installing one of these OpenSSL binaries didn't alleviate it, and it did not supply me with any DLLs.

I can see a library called `qopensslbackend.dll` in `(Prism folder)/tls`. This suggests me that OpenSSL is bundled with Prism for Windows. (Out of curiosity, I swapped it with another version from Nekoray - it made no difference.)

**Comment by Trial97** [comment]
then try the other stuff related to the certificates I mentioned previously.
I found that the error message is from the openssl library and may be due to certificate issues.

**Comment by khankul** [comment]
Using the wikihow article, I did the following:
1. Open Internet Options window (`rundll32.exe shell32.dll,Control_RunDLL inetcpl.cpl`)
2. On Advanced tab, uncheck *Check for publisher's certificate revocation* and *Check for server certificate revocation*
3. On Content tab, click *Clear SSL state*
4. Reboot

After this, Prism has finally connected to the internet. Yay.
Interestingly, though I turned the certificate revocation checks back on and rebooted again, Prism can still connect to the services, fetch versions list etc. I'm inclined to make a conclusion that only clearing SSL state and rebooting afterwards is required to fix this. I will ask my friend who has the same issue to see if they can reproduce the fix.

**Comment by khankul** [comment]
@Trial97 I've done some digging together with my friend. Turns out the steps described above weren't needed at all (although I'm not sure about clearing SSH cache...), and what was needed is indeed some [OpenSSL binaries](https://kb.firedaemon.com/support/solutions/articles/4000121705l). So you were right from the start. **Important note: you have to allow it to include openssl.exe into PATH during installation**, otherwise it will not work. Unfortunately this will only work for the nightly builds you've sent - "stable" Prism installations were not fixed by this.
Also, we both used Windows 10 Enterprise LTSC 2016. I do not recall having this issue with a regular (and more modern) Enterprise installation. I should test this on a separate LTSC installation later.

**Comment by Trial97** [comment]
Thank you for your response. I hope this may help the other people who are having similar problems.
