### ISSUE TITLE
Launcher crashes with RandomPatches on 1.12.2

### ISSUE THREAD

**Issue by spikespaz** [PrismLauncher/PrismLauncher#1267]
### Operating System

Linux

### Version of Prism Launcher

bcf45c74a1b0b3389c05927637bf8aa95b8e43cf (8.0)

### Version of Qt

Qt 5.15.9

### Description of bug

The game was launching fine before, but it seems that after updating Wayland, Hyprland, and Mesa, I am getting this error.

```
Exception caught from launcher
java.lang.ExceptionInInitializerError
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.<init>(ASMTransformerWrapper.java:243)
	at $wrapper.com.therandomlabs.randompatches.core.RPTransformer.<init>(Unknown Source)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88)
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:132)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Caused by: net.minecraft.util.ReportedException: Failed to reload configuration category
	at com.therandomlabs.randompatches.repackage.com.therandomlabs.randomlib.TRLUtils.crashReport(TRLUtils.java:183)
	at com.therandomlabs.randompatches.repackage.com.therandomlabs.randomlib.config.TRLCategory.onReload(TRLCategory.java:42)
	at com.therandomlabs.randompatches.repackage.com.therandomlabs.randomlib.config.ConfigManager.writeToDisk(ConfigManager.java:160)
	at com.therandomlabs.randompatches.repackage.com.therandomlabs.randomlib.config.ConfigManager.reloadFromConfig(ConfigManager.java:144)
	at com.therandomlabs.randompatches.repackage.com.therandomlabs.randomlib.config.ConfigManager.reloadFromDisk(ConfigManager.java:93)
	at com.therandomlabs.randompatches.repackage.com.therandomlabs.randomlib.config.ConfigManager.register(ConfigManager.java:86)
	at com.therandomlabs.randompatches.core.RPTransformer.<clinit>(RPTransformer.java:18)
	... 19 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.therandomlabs.randompatches.repackage.com.therandomlabs.randomlib.config.TRLCategory.onReload(TRLCategory.java:40)
	... 24 more
Caused by: java.lang.ExceptionInInitializerError
	at com.therandomlabs.randompatches.config.RPConfig$Window.onReloadClient(RPConfig.java:396)
	... 29 more
Caused by: java.lang.NullPointerException
	at org.lwjgl.opengl.XRandR.getConfiguration(XRandR.java:146)
	at org.lwjgl.opengl.LinuxDisplay$3.run(LinuxDisplay.java:746)
	at org.lwjgl.opengl.LinuxDisplay$3.run(LinuxDisplay.java:743)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lwjgl.opengl.LinuxDisplay.init(LinuxDisplay.java:743)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:138)
	... 30 more
Exiting with ERROR
Exception in thread "main" [18:47:33] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[18:47:33] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[18:47:33] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[18:47:33] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
[18:47:33] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:973)
[18:47:33] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:76)
```

### Steps to reproduce

This will be trouble to reproduce because I use a NixOS config. I can provide more details and a modpack if required.

### Suspected cause

RandomPatches

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by telans** [comment]
This isn't an issue with the launcher, but with minecraft. Regardless, have you restarted your computer since updating? Seems like a driver issue:

```
Caused by: java.lang.NullPointerException
	at org.lwjgl.opengl.XRandR.getConfiguration(XRandR.java:146)
```

Is there proper output if you run `xrandr` yourself?

**Comment by spikespaz** [comment]
> Is there proper output if you run xrandr yourself?

I use wayland + xwayland so no.
