### ISSUE TITLE
Minecraft threatens to start but crashes

### ISSUE THREAD

**Issue by fer0li** [PrismLauncher/PrismLauncher#1315]
### Operating System

Artix Linux (with dinit + nvidia 340.108)

### Version of Prism Launcher

Prism Launcher 7.1

### Version of Qt

Qt 6.5.1

### Description of bug

I click start the game window appears, but then closes (Version 1.8.9 works normally)

### Steps to reproduce

I create an instance in version 1.20.1 and click on launch

### Suspected cause

Log launcher:
```
Prism Launcher version: 7.1


Launched instance in online mode

authserver.mojang.com resolves to:
    [108.158.147.35, 108.158.147.40, 108.158.147.59, 108.158.147.12]

session.minecraft.net resolves to:
    [13.107.246.33, 13.107.213.33, 2620:1ec:bdf::33, 2620:1ec:46::33]

textures.minecraft.net resolves to:
    [13.107.246.33, 13.107.213.33, 2620:1ec:bdf::33, 2620:1ec:46::33]

api.mojang.com resolves to:
    [13.107.246.33, 13.107.213.33, 2620:1ec:bdf::33, 2620:1ec:46::33]


Minecraft folder is:
/home/feroli/.local/share/PrismLauncher/instances/1.20.1/.minecraft


Java path is:
/usr/lib/jvm/java-17-jdk/bin/java


Java is version 17.0.7, using 64 (amd64) architecture, from Oracle Corporation.


Pentium(R) Dual-Core  CPU      E5400  @ 2.70GHz
NVIDIA Corporation G96C [GeForce 9500 GT] (rev a1)

Subsystem: Elitegroup Computer Systems G96C [GeForce 9500 GT]

Kernel driver in use: nvidia

OpenGL version string: 3.3.0 NVIDIA 340.108

Main Class:
  net.minecraft.client.main.Main

Native path:
  /home/feroli/.local/share/PrismLauncher/instances/1.20.1/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  /home/feroli/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-glfw-natives-linux/3.3.2-lwjgl.1/lwjgl-glfw-natives-linux-3.3.2-lwjgl.1.jar
  /home/feroli/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1.jar
  /home/feroli/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-jemalloc-natives-linux/3.3.1/lwjgl-jemalloc-natives-linux-3.3.1.jar
  /home/feroli/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1.jar
  /home/feroli/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-natives-linux/3.3.1/lwjgl-natives-linux-3.3.1.jar
  /home/feroli/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-openal-natives-linux/3.3.1/lwjgl-openal-natives-linux-3.3.1.jar
  /home/feroli/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1.jar
  /home/feroli/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-opengl-natives-linux/3.3.1/lwjgl-opengl-natives-linux-3.3.1.jar
  /home/feroli/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1.jar
  /home/feroli/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-stb-natives-linux/3.3.1/lwjgl-stb-natives-linux-3.3.1.jar
  /home/feroli/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1.jar
  /home/feroli/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-tinyfd-natives-linux/3.3.1/lwjgl-tinyfd-natives-linux-3.3.1.jar
  /home/feroli/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1.jar
  /home/feroli/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1.jar
  /home/feroli/.local/share/PrismLauncher/libraries/com/github/oshi/oshi-core/6.2.2/oshi-core-6.2.2.jar
  /home/feroli/.local/share/PrismLauncher/libraries/com/google/code/gson/gson/2.10/gson-2.10.jar
  /home/feroli/.local/share/PrismLauncher/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  /home/feroli/.local/share/PrismLauncher/libraries/com/google/guava/guava/31.1-jre/guava-31.1-jre.jar
  /home/feroli/.local/share/PrismLauncher/libraries/com/ibm/icu/icu4j/71.1/icu4j-71.1.jar
  /home/feroli/.local/share/PrismLauncher/libraries/com/mojang/authlib/4.0.43/authlib-4.0.43.jar
  /home/feroli/.local/share/PrismLauncher/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  /home/feroli/.local/share/PrismLauncher/libraries/com/mojang/brigadier/1.1.8/brigadier-1.1.8.jar
  /home/feroli/.local/share/PrismLauncher/libraries/com/mojang/datafixerupper/6.0.8/datafixerupper-6.0.8.jar
  /home/feroli/.local/share/PrismLauncher/libraries/com/mojang/logging/1.1.1/logging-1.1.1.jar
  /home/feroli/.local/share/PrismLauncher/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  /home/feroli/.local/share/PrismLauncher/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar
  /home/feroli/.local/share/PrismLauncher/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  /home/feroli/.local/share/PrismLauncher/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  /home/feroli/.local/share/PrismLauncher/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  /home/feroli/.local/share/PrismLauncher/libraries/io/netty/netty-buffer/4.1.82.Final/netty-buffer-4.1.82.Final.jar
  /home/feroli/.local/share/PrismLauncher/libraries/io/netty/netty-codec/4.1.82.Final/netty-codec-4.1.82.Final.jar
  /home/feroli/.local/share/PrismLauncher/libraries/io/netty/netty-common/4.1.82.Final/netty-common-4.1.82.Final.jar
  /home/feroli/.local/share/PrismLauncher/libraries/io/netty/netty-handler/4.1.82.Final/netty-handler-4.1.82.Final.jar
  /home/feroli/.local/share/PrismLauncher/libraries/io/netty/netty-resolver/4.1.82.Final/netty-resolver-4.1.82.Final.jar
  /home/feroli/.local/share/PrismLauncher/libraries/io/netty/netty-transport-classes-epoll/4.1.82.Final/netty-transport-classes-epoll-4.1.82.Final.jar
  /home/feroli/.local/share/PrismLauncher/libraries/io/netty/netty-transport-native-epoll/4.1.82.Final/netty-transport-native-epoll-4.1.82.Final-linux-aarch_64.jar
  /home/feroli/.local/share/PrismLauncher/libraries/io/netty/netty-transport-native-epoll/4.1.82.Final/netty-transport-native-epoll-4.1.82.Final-linux-x86_64.jar
  /home/feroli/.local/share/PrismLauncher/libraries/io/netty/netty-transport-native-unix-common/4.1.82.Final/netty-transport-native-unix-common-4.1.82.Final.jar
  /home/feroli/.local/share/PrismLauncher/libraries/io/netty/netty-transport/4.1.82.Final/netty-transport-4.1.82.Final.jar
  /home/feroli/.local/share/PrismLauncher/libraries/it/unimi/dsi/fastutil/8.5.9/fastutil-8.5.9.jar
  /home/feroli/.local/share/PrismLauncher/libraries/net/java/dev/jna/jna-platform/5.12.1/jna-platform-5.12.1.jar
  /home/feroli/.local/share/PrismLauncher/libraries/net/java/dev/jna/jna/5.12.1/jna-5.12.1.jar
  /home/feroli/.local/share/PrismLauncher/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  /home/feroli/.local/share/PrismLauncher/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  /home/feroli/.local/share/PrismLauncher/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  /home/feroli/.local/share/PrismLauncher/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  /home/feroli/.local/share/PrismLauncher/libraries/org/apache/httpcomponents/httpcore/4.4.15/httpcore-4.4.15.jar
  /home/feroli/.local/share/PrismLauncher/libraries/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar
  /home/feroli/.local/share/PrismLauncher/libraries/org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar
  /home/feroli/.local/share/PrismLauncher/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar
  /home/feroli/.local/share/PrismLauncher/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar
  /home/feroli/.local/share/PrismLauncher/libraries/org/slf4j/slf4j-api/2.0.1/slf4j-api-2.0.1.jar
  /home/feroli/.local/share/PrismLauncher/libraries/com/mojang/minecraft/1.20.1/minecraft-1.20.1-client.jar

Native libraries:

Params:
  --username  --version 1.20.1 --gameDir /home/feroli/.local/share/PrismLauncher/instances/1.20.1/.minecraft --assetsDir /home/feroli/.local/share/PrismLauncher/assets --assetIndex 5 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Launcher: standard

Java Arguments:
[-Xms512m, -Xmx1984m, -Duser.language=en]


Minecraft process ID: 3990


[13:58:32] [Datafixer Bootstrap/INFO]: 188 Datafixer optimizations took 787 milliseconds
[13:58:38] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[13:58:40] [Render thread/INFO]: Setting user: Feroli
[13:58:40] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 build 7
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!
Time: 2023-07-05 13:58:44
Description: Initializing game
java.lang.IllegalStateException: There is no OpenGL context current in the current thread.
	at org.lwjgl.opengl.GL.createCapabilities(GL.java:385)
	at org.lwjgl.opengl.GL.createCapabilities(GL.java:314)
	at org.lwjgl.opengl.GL.createCapabilities(GL.java:298)
	at ehn.<init>(SourceFile:113)
	at fkm.a(SourceFile:21)
	at enn.<init>(SourceFile:486)
	at net.minecraft.client.main.Main.main(SourceFile:211)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: Render thread
Stacktrace:
	at org.lwjgl.opengl.GL.createCapabilities(GL.java:385)
	at org.lwjgl.opengl.GL.createCapabilities(GL.java:314)
	at org.lwjgl.opengl.GL.createCapabilities(GL.java:298)
	at ehn.<init>(SourceFile:113)
	at fkm.a(SourceFile:21)
	at enn.<init>(SourceFile:486)
-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:211)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (amd64) version 6.4.1-artix1-1
	Java Version: 17.0.7, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 358075904 bytes (341 MiB) / 536870912 bytes (512 MiB) up to 2080374784 bytes (1984 MiB)
	CPUs: 2
	Processor Vendor: GenuineIntel
	Processor Name: Pentium(R) Dual-Core  CPU      E5400  @ 2.70GHz
	Identifier: Intel64 Family 6 Model 23 Stepping 10
	Microarchitecture: Penryn (Client) / Penryn (Server)
	Frequency (GHz): 2.70
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 2
	Graphics card #0 name: G96C [GeForce 9500 GT]
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MB): 512.00
	Graphics card #0 deviceId: 0x0640
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 4270.55
	Virtual memory used (MB): 2858.23
	Swap memory total (MB): 2782.41
	Swap memory used (MB): 683.61
	JVM Flags: 2 total; -Xms512m -Xmx1984m
	Launched Version: 1.20.1
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Probably not. Client jar signature and brand is untouched
	Type: Client (map_client.txt)
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# /home/feroli/.local/share/PrismLauncher/instances/1.20.1/.minecraft/crash-reports/crash-2023-07-05_13.58.44-client.txt
Process exited with code 255.
Clipboard copy at: 05 Jul 2023 13:58:49 -0300
```

Log file:
```
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 2023-07-05 13:32:31
Description: Initializing game

java.lang.IllegalStateException: There is no OpenGL context current in the current thread.
	at org.lwjgl.opengl.GL.createCapabilities(GL.java:385)
	at org.lwjgl.opengl.GL.createCapabilities(GL.java:314)
	at org.lwjgl.opengl.GL.createCapabilities(GL.java:298)
	at ehn.<init>(SourceFile:113)
	at fkm.a(SourceFile:21)
	at enn.<init>(SourceFile:486)
	at net.minecraft.client.main.Main.main(SourceFile:211)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.lwjgl.opengl.GL.createCapabilities(GL.java:385)
	at org.lwjgl.opengl.GL.createCapabilities(GL.java:314)
	at org.lwjgl.opengl.GL.createCapabilities(GL.java:298)
	at ehn.<init>(SourceFile:113)
	at fkm.a(SourceFile:21)
	at enn.<init>(SourceFile:486)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:211)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (amd64) version 6.4.1-artix1-1
	Java Version: 17.0.7, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 353918976 bytes (337 MiB) / 536870912 bytes (512 MiB) up to 2080374784 bytes (1984 MiB)
	CPUs: 2
	Processor Vendor: GenuineIntel
	Processor Name: Pentium(R) Dual-Core  CPU      E5400  @ 2.70GHz
	Identifier: Intel64 Family 6 Model 23 Stepping 10
	Microarchitecture: Penryn (Client) / Penryn (Server)
	Frequency (GHz): 2.70
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 2
	Graphics card #0 name: G96C [GeForce 9500 GT]
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MB): 512.00
	Graphics card #0 deviceId: 0x0640
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 4270.55
	Virtual memory used (MB): 2652.37
	Swap memory total (MB): 2782.41
	Swap memory used (MB): 639.25
	JVM Flags: 2 total; -Xms512m -Xmx1984m
	Launched Version: 1.20.1
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Probably not. Client jar signature and brand is untouched
	Type: Client (map_client.txt)
	CPU: <unknown>
```

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by BroPro40** [comment]
Hello, I have the same issue ( artix linux dinit + amd gpu pro drivers )
wiht opensource driverseverything works fine

**Comment by Ryex** [comment]
> Hello, I have the same issue ( artix linux dinit + amd gpu pro drivers ) wiht opensource driverseverything works fine

That would be a driver issue and not something the launcher can fix. The proprietary drivers are known to try and optimize known games in ways that can breaks new or old versions.

@VictorFeroli  Are you using the proprietary nvidia drivers? do other launchers like ATLauncher crash in the same way?

**Comment by fer0li** [comment]
> > Hello, I have the same issue ( artix linux dinit + amd gpu pro drivers ) wiht opensource driverseverything works fine
> 
> That would be a driver issue and not something the launcher can fix. The proprietary drivers are known to try and optimize known games in ways that can breaks new or old versions.
> 
> @VictorFeroli Are you using the proprietary nvidia drivers? do other launchers like ATLauncher crash in the same way?

Yes, I am using nvidia proprietary driver. No, in other launchers the game runs normally.

**Comment by Michael567282** [comment]
I am experiencing the same problem, except it only happens when I try to launch a 1.21 instance. Any instances from an older Minecraft version works.

**Comment by YeesterPlus** [comment]
install graphics drivers

**Comment by Octol1ttle** [comment]
Not a launcher issue, if you're using NVIDIA and the Flatpak version of Prism Launcher, you need to run `flatpak update` after driver updates/installations for them to work inside Flatpak apps
