### ISSUE TITLE
Minecraft not launching on apple silicon

### ISSUE THREAD

**Issue by starcraft66** [PrismLauncher/PrismLauncher#156]
### Operating System

macOS

### Version of PolyMC

Prism Launcher 5.0

### Version of Qt

Qt 6.3.0

### Description of bug

Minecraft instances do not launch at all on apple silicon.

When launching minecraft a1.2.1_01:
```
Exception in thread "Minecraft main thread" java.lang.UnsatisfiedLinkError: no lwjgl in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1875)
	at java.lang.Runtime.loadLibrary0(Runtime.java:872)
	at java.lang.System.loadLibrary(System.java:1124)
	at org.lwjgl.Sys$1.run(Sys.java:72)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
	at org.lwjgl.Sys.loadLibrary(Sys.java:96)
	at org.lwjgl.Sys.<clinit>(Sys.java:117)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:135)
	at net.minecraft.client.Minecraft.a(SourceFile:150)
	at net.minecraft.client.Minecraft.run(SourceFile:560)
	at java.lang.Thread.run(Thread.java:750)
```

When launching 1.19.2:
```
[22:09:26] [Render thread/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.9.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176) [NewLaunch.jar:?]
	at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:74) [NewLaunch.jar:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
	at net.minecraft.class_6396.method_37123(class_6396.java:66) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_37274(class_310.java:2359) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_22681(class_310.java:2354) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:214) ~[minecraft-1.19.2-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[minecraft-1.19.2-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.9.jar:?]
	... 11 more
```

### Steps to reproduce

Create a minecraft instance on an apple silicon computer and try launching the game. 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jschenke488** [comment]
Did you test to see if it launches on vanilla 1.19.2? The exception with a1.2.1_01 is very likely a bug with Prism though

**Comment by jschenke488** [comment]
I would also suggest trying to download a newer version of Java

**Comment by alexyao2015** [comment]
I'm hitting the exact same issue and previously had no issues on 1.4.2 of PolyMC.

**Comment by r58Playz** [comment]
> ### Operating System
> 
> macOS
> ### Version of PolyMC
> 
> Prism Launcher 5.0
> ### Version of Qt
> 
> Qt 6.3.0
> ### Description of bug
> 
> Minecraft instances do not launch at all on apple silicon.
> 
> When launching minecraft a1.2.1_01:
> 
> ```
> Exception in thread "Minecraft main thread" java.lang.UnsatisfiedLinkError: no lwjgl in java.library.path
> 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1875)
> 	at java.lang.Runtime.loadLibrary0(Runtime.java:872)
> 	at java.lang.System.loadLibrary(System.java:1124)
> 	at org.lwjgl.Sys$1.run(Sys.java:72)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66)
> 	at org.lwjgl.Sys.loadLibrary(Sys.java:96)
> 	at org.lwjgl.Sys.<clinit>(Sys.java:117)
> 	at org.lwjgl.opengl.Display.<clinit>(Display.java:135)
> 	at net.minecraft.client.Minecraft.a(SourceFile:150)
> 	at net.minecraft.client.Minecraft.run(SourceFile:560)
> 	at java.lang.Thread.run(Thread.java:750)
> ```
> 
> When launching 1.19.2:
> 
> ```
> [22:09:26] [Render thread/ERROR]: Minecraft has crashed!
> net.fabricmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.9.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.9.jar:?]
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
> 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
> 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
> 	at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
> 	at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176) [NewLaunch.jar:?]
> 	at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186) [NewLaunch.jar:?]
> 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144) [NewLaunch.jar:?]
> 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:74) [NewLaunch.jar:?]
> Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
> 	at net.minecraft.class_6396.method_37123(class_6396.java:66) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_310.method_37274(class_310.java:2359) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_310.method_22681(class_310.java:2354) ~[client-intermediary.jar:?]
> 	at net.minecraft.client.main.Main.method_44604(Main.java:214) ~[minecraft-1.19.2-client.jar:?]
> 	at net.minecraft.client.main.Main.main(Main.java:51) ~[minecraft-1.19.2-client.jar:?]
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.9.jar:?]
> 	... 11 more
> ```
> 
> ### Steps to reproduce
> 
> Create a minecraft instance on an apple silicon computer and try launching the game.
> ### Suspected cause
> 
> _No response_
> ### This issue is unique
> 
>     * [x]  I have searched the issue tracker and did not find an issue describing my bug.

don't use ManyMC meta, remove the meta folder as well

**Comment by starcraft66** [comment]
Forgot to mention, this happens when I rename my ManyMC folder to PrismLauncher. If I let the launcher create a new PrismLauncher folder everything works.

**Comment by r58Playz** [comment]
please don't use manymc metaserver, remove your meta folder as well

**Comment by starcraft66** [comment]
Okay, deleting the meta folder works. Thanks.

**Comment by AlexanderwithaA** [comment]
I'm having an issue like this as well, trying to run fabric, crashes even with no mods enabled. Old mac with intel chip not a new M1.
```
[21:39:38] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[21:39:38] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[21:39:38] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[21:39:38] [Render thread/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[21:39:40] [Render thread/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.10.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176) [NewLaunch.jar:?]
	at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:74) [NewLaunch.jar:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
	at net.minecraft.class_6396.method_37123(class_6396.java:65) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_37274(class_310.java:2394) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_22681(class_310.java:2389) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:206) ~[minecraft-1.18.2-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.10.jar:?]
	... 11 more
Process exited with code 1.

**Comment by omerien** [comment]
Did you delete the meta folder ?

**Comment by AlexanderwithaA** [comment]
just deleted it, restarted prism launcher still crashes. I am trying to use fabric to run vulkan renderer.
