### ISSUE TITLE
Adding more than one version of Forge causes "Failed to run processor: java.net.ConnectException:Connection refused See log for more details"

### ISSUE THREAD

**Issue by Handrail9** [PrismLauncher/PrismLauncher#1623]
### Operating System
Fedora 38 KDE Spin, Flatpak

### Version of Prism Launcher

Prism Launcher 7.2
Flatpak stable, 2023-07-26

### Version of Qt

Qt 5.15.10

### Description of bug

Starting with the recommended version of forge for 1.19.4 (45.1.0) and adding another instance with _any other_ version of forge for 1.19.4 causes the Failed to run processor: java.net.ConnectException:Connection refused See log for more details window to show

### Steps to reproduce

Create an instance of 1.19.4 forge with recommended version, then make an instance with anything after recommend forge for 1.19.4

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### Console Logs
`java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:579)
	at java.base/sun.nio.ch.Net.connect(Net.java:568)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at java.base/java.net.URL.openStream(URL.java:1161)
	at net.minecraftforge.installertools.DownloadMojmaps.process(DownloadMojmaps.java:65)
	at net.minecraftforge.installertools.ConsoleTool.main(ConsoleTool.java:55)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.minecraftforge.installer.actions.PostProcessors.process(PostProcessors.java:226)
	at io.github.zekerzhayard.forgewrapper.installer.util.InstallerV1$ClientInstall4MultiMC.run(InstallerV1.java:35)
	at io.github.zekerzhayard.forgewrapper.installer.util.InstallerV1.runClientInstall(InstallerV1.java:20)
	at io.github.zekerzhayard.forgewrapper.installer.Installer.install(Installer.java:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:51)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Process was killed by user.`

**Comment by Trial97** [comment]
Hi @Wave6677 can you please upload the full log( but please use https://mclo.gs/ as they are easier to read there)
Also from the current log, it looks like you manually stopped the process.

**Comment by Handrail9** [comment]
Forgot I opened this issue, did a flatpak update recently, and the error no longer occurs. Closing for now but will reopen if I can recreate it
