### ISSUE TITLE
In Game folder cannot be opened in Minecraft version 1.18 and above

### ISSUE THREAD

**Issue by weearc** [PrismLauncher/PrismLauncher#1648]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 7.2 (From pre-built-mpr suggested in document)

### Version of Qt

Qt 5.15.10

### Description of bug

When launcher a version above 1.18 of vanilla minecraft, and press open resource folder button, will get following errors:
```txt
java.security.PrivilegedActionException: null
	at java.security.AccessController.doPrivileged(AccessController.java:573) ~[?:?]
	at net.minecraft.class_156$class_158.method_669(class_156.java:313) ~[client-intermediary.jar:?]
	at net.minecraft.class_156$class_158.method_673(class_156.java:324) ~[client-intermediary.jar:?]
	at net.minecraft.class_5375.method_29670(class_5375.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:56) ~[client-intermediary.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:189) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:409) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:169) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.redirect$foc001$viafabricplus$redirectSync(class_312.java:3538) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:169) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474) ~[lwjgl-glfw-3.3.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:237) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1244) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
Caused by: java.io.IOException: Cannot run program "xdg-open": error=13, 权限不够
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1143) ~[?:?]
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1073) ~[?:?]
	at java.lang.Runtime.exec(Runtime.java:594) ~[?:?]
	at java.lang.Runtime.exec(Runtime.java:453) ~[?:?]
	at net.minecraft.class_156$class_158.method_671(class_156.java:313) ~[client-intermediary.jar:?]
	at java.security.AccessController.doPrivileged(AccessController.java:569) ~[?:?]
	... 27 more
Caused by: java.io.IOException: error=13, 权限不够
	at java.lang.ProcessImpl.forkAndExec(Native Method) ~[?:?]
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:314) ~[?:?]
	at java.lang.ProcessImpl.start(ProcessImpl.java:244) ~[?:?]
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1110) ~[?:?]
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1073) ~[?:?]
	at java.lang.Runtime.exec(Runtime.java:594) ~[?:?]
	at java.lang.Runtime.exec(Runtime.java:453) ~[?:?]
	at net.minecraft.class_156$class_158.method_671(class_156.java:313) ~[client-intermediary.jar:?]
	at java.security.AccessController.doPrivileged(AccessController.java:569) ~[?:?]
	... 27 more
```

### Steps to reproduce

As described above, open Minecraft version 1.18 and above , go to settings - resource pack - open resource folder , and it won't open any folders

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Not a PrismLauncher issue(as it's the in-game button).
But from the logs it looks like you do not have xdg-open: install xdg-desktop-portal and a backend for it,  more info about it you can find here:https://wiki.archlinux.org/title/XDG_Desktop_Portal

**Comment by weearc** [comment]
> Not a PrismLauncher issue(as it's the in-game button). But from the logs it looks like you do not have xdg-open: install xdg-desktop-portal and a backend for it, more info about it you can find here:https://wiki.archlinux.org/title/XDG_Desktop_Portal

Hi, thank you for quick reply. I do have xdg-desktop-portal installed :
![image](https://github.com/PrismLauncher/PrismLauncher/assets/19357165/3bb03f6c-1f7e-4ee9-a9bd-84e099932646)

Is this a bug from Mojang perhaps? But I also tried on Arch Linux with a qt6 version and can successfully open in game folder. Is there any ways to locate this issue?

**Comment by Trial97** [comment]
Not so sure, maybe minecraft tracker: https://bugs.mojang.com/projects/MC/summary
Also if it works on the other system check the file/folder permissions

**Comment by weearc** [comment]
@Trial97 Hi, I finally found out this is about apparmor enabled by default on debian. This problem  is solved.
