### ISSUE TITLE
Forge 1.20.3 isn't starting/launching

### ISSUE THREAD

**Issue by Stein-N** [PrismLauncher/PrismLauncher#2128]
### Version of Prism Launcher

Prism Launcher 8.0

### Version of Qt

Qt 6.6.0

### Description of bug

Forge for Minecraft 1.20.3 can't be launched, because the "Library Directory doesn't exist"

```console 
Checking: MERGED_MAPPINGS
Checking: MAPPINGS
Checking: MOJMAPS
Checking: PATCHED
Checking: MC_SRG
2024-02-13 20:46:59,687 main WARN Advanced terminal features are not available in this environment
[20:46:59] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, xStopho, --version, 1.20.3, --gameDir, C:/Users/stein/AppData/Roaming/PrismLauncher/instances/Forge 1.20.3/.minecraft, --assetsDir, C:/Users/stein/AppData/Roaming/PrismLauncher/assets, --assetIndex, 12, --uuid, <PROFILE ID>, --accessToken, **********, --userType, msa, --versionType, release, --launchTarget, forge_client, --fml.forgeGroup, net.minecraftforge, --fml.forgeVersion, 49.0.1, --fml.mcVersion, 1.20.3, --width, 810, --height, 484]
[20:46:59] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: JVM identified as Eclipse Adoptium OpenJDK 64-Bit Server VM 17.0.9+9
[20:46:59] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.1.2 starting: java version 17.0.9 by Eclipse Adoptium; OS Windows 11 arch amd64 version 10.0
[20:47:00] [main/INFO] [ne.mi.fm.lo.ImmediateWindowHandler/]: Loading ImmediateWindowProvider fmlearlywindow
[20:47:00] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.6
[20:47:00] [main/INFO] [EARLYDISPLAY/]: Requested GL version 4.6 got version 4.6
[20:47:00] [EarlyDisplay/INFO] [EARLYDISPLAY/]: GL info: NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 551.23, NVIDIA Corporation
[20:47:00] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=jar:file:///C:/Users/stein/AppData/Roaming/PrismLauncher/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar!/ Service=ModLauncher Env=CLIENT
Exception caught from launcher
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.minecraftforge.bootstrap.Bootstrap.start(Bootstrap.java:48)
	at net.minecraftforge.bootstrap.ForgeBootstrap.main(ForgeBootstrap.java:18)
	... 8 more
Caused by: java.lang.IllegalStateException: Library directory: `libraries` does not exist. Set it via the `libraryDirectory` system property.
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.20.3-49.0.1/net.minecraftforge.fml.loading.LibraryFinder.findLibsPath(LibraryFinder.java:17)
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.20.3-49.0.1/net.minecraftforge.fml.loading.LibraryFinder.findPathForMaven(LibraryFinder.java:23)
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.20.3-49.0.1/net.minecraftforge.fml.loading.targets.ForgeProdLaunchHandler.getMinecraftPaths(ForgeProdLaunchHandler.java:27)
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.20.3-49.0.1/net.minecraftforge.fml.loading.targets.ForgeProdLaunchHandler$Client.getMinecraftPaths(ForgeProdLaunchHandler.java:31)
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.20.3-49.0.1/net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator.scanMods(MinecraftLocator.java:24)
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.20.3-49.0.1/net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer.discoverMods(ModDiscoverer.java:78)
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.20.3-49.0.1/net.minecraftforge.fml.loading.FMLLoader.beginModScan(FMLLoader.java:154)
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.20.3-49.0.1/net.minecraftforge.fml.loading.FMLServiceProvider.beginScanning(FMLServiceProvider.java:58)
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.1.2/cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:98)
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.1.2/cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$7(TransformationServicesHandler.java:96)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.1.2/cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:98)
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.1.2/cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:49)
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.1.2/cpw.mods.modlauncher.Launcher.run(Launcher.java:86)
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.1.2/cpw.mods.modlauncher.Launcher.main(Launcher.java:73)
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.1.2/cpw.mods.modlauncher.BootstrapEntry.main(BootstrapEntry.java:17)
	at net.minecraftforge.bootstrap@2.0.0/net.minecraftforge.bootstrap.Bootstrap.moduleMain(Bootstrap.java:97)
	... 14 more
Exiting with ERROR
Process exited with code 2.
```

### Steps to reproduce

1. Create a new instance with Forge for Minecraft 1.20.3.
2. Start it with an Microsoft account
3. Forge crashes

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
This is most probably related to https://github.com/PrismLauncher/PrismLauncher/issues/1934

**Comment by Stein-N** [comment]
As an addition this error appears on the follwoing Forge Versions:

- 1.20.3
  - 49.0.1
  - 49.0.2
- 1.20.4
  - 49.0.3

**Comment by Stein-N** [comment]
When i set the java argument:

-DlibraryDirectory=C:\Users\USER\AppData\Roaming\PrismLauncher\libraries

all versions above works fine, so i think internaly those arguments are missing?

**Comment by Stein-N** [comment]
Closing the issue because of an outdated, not commonly used Minecraft version.
