### ISSUE TITLE
Error 255

### ISSUE THREAD

**Issue by MisTerio497** [PrismLauncher/PrismLauncher#2143]
### Operating System

Linux

### Version of Prism Launcher

8.0-develop

### Version of Qt

6.6.2

### Description of bug

For some reason, I can't run minecraft below 1.13 version, error 255 comes out.
Here are the crash report:
---- Minecraft Crash Report ----
// I feel sad now :(

Time: 2/19/24 7:17 PM
Description: Initializing game

java.lang.ExceptionInInitializerError
	at bao.ag(SourceFile:299)
	at bao.f(SourceFile:713)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at org.lwjgl.opengl.LinuxDisplay.getAvailableDisplayModes(LinuxDisplay.java:951)
	at org.lwjgl.opengl.LinuxDisplay.init(LinuxDisplay.java:738)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:138)
	... 6 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at bao.ag(SourceFile:299)

-- Initialization --
Details:
Stacktrace:
	at bao.f(SourceFile:713)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 6.7.5-zen1-1-zen
	Java Version: 1.8.0_402, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 486256496 bytes (463 MB) / 514850816 bytes (491 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 2 total; -Xms512m -Xmx4096m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.7.10
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: 
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

### Steps to reproduce

The launch of Minecraft version below 1.13

### Suspected cause

Most likely, I did not add something to the system

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Can you provide the full logs:
Please send logs! The recommended site to upload your logs to is [mclo.gs](https://mclo.gs/).
![image](https://github.com/PrismLauncher/PrismLauncher/assets/42720688/4e4fe260-d891-4ab2-b928-1ac3ed89ae53)

**Comment by MisTerio497** [comment]
I have already figured out the reason for the error. I haven't finished installing **xorg-xrandr**.
