### ISSUE TITLE
Minecraft Failing to launch on OpenBSD

### ISSUE THREAD

**Issue by ezntek** [PrismLauncher/PrismLauncher#2296]
### Operating System

Other

### Version of Prism Launcher

Prism Launcher 9.0-develop

### Version of Qt

Qt 6.6.1

### Description of bug

On OpenBSD, when trying to launch minecraft, the launcher catches an exception:

```
Exception caught from launcher
java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
	at ac.a(SourceFile:66)
	at fgj.a(SourceFile:2622)
	at fgj.a(SourceFile:2597)
	at net.minecraft.client.main.Main.main(SourceFile:233)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.LinkageError: Unknown platform: OpenBSD [in thread "Render thread"]
	at org.lwjgl.system.Platform.<clinit>(Platform.java:91)
	at org.lwjgl.system.Library.<clinit>(Library.java:33)
	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:100)
	at faa.<clinit>(SourceFile:8)
	at fax.<init>(SourceFile:49)
	at fbe.<init>(SourceFile:33)
	at com.mojang.blaze3d.systems.RenderSystem.<clinit>(SourceFile:50)
	at net.minecraft.client.main.Main.main(SourceFile:220)
	... 3 more
Exiting with ERROR
Process exited with code 2.
```

I'm running the latest stable release of the operating system, 7.5. LWJGL3 is from the ports. This issue does also happen on the latest release of Prism Launcher.

### Steps to reproduce

* Compile 9.0-develop from source
* Add your account
* Add an instance
* Launch
* Error

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
There were some omissions in the reproduction steps:
- what kind of account did you add?
- on what version did you create the instance?
- did you install a loader?
- can you provide the full log instead of just part of it?

From what I understand from the limited log this is an issue with the meta try:
- ensure that the meta API URL is empty (found in settings>apis>services>Metadata server)
- if you started in offline mode: click on the instance>edit>versions>Download all

**Comment by ezntek** [comment]
> What kind of account did you add?

an offline account.

> On what version did you create the instance?

I created the instance on 9.0-develop, and re-created it after downgrading to 8.2.

> Did you install a loader?

No.

> Can you provide the full log instead of just part of it?

```
Prism Launcher version: 8.2 (unknown)


Launched instance in online mode

authserver.mojang.com resolves to:
    [N/A]

session.minecraft.net resolves to:
    [13.107.246.59, 13.107.213.59]

textures.minecraft.net resolves to:
    [13.107.246.59, 13.107.213.59]

api.mojang.com resolves to:
    [13.107.213.59, 13.107.246.59]


Minecraft folder is:
/home/ezntek/.local/share/PrismLauncher/instances/1.20.4/.minecraft


Java path is:
/usr/local/jdk-17/bin/java


Java is version 17.0.10, using 64 (amd64) architecture, from N/A.


Main Class:
  net.minecraft.client.main.Main

Native path:
  /home/ezntek/.local/share/PrismLauncher/instances/1.20.4/natives

Traits:
traits feature:is_quick_play_multiplayer
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  /home/ezntek/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-freetype/3.3.2/lwjgl-freetype-3.3.2.jar
  /home/ezntek/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-glfw/3.3.2/lwjgl-glfw-3.3.2.jar
  /home/ezntek/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-jemalloc/3.3.2/lwjgl-jemalloc-3.3.2.jar
  /home/ezntek/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-openal/3.3.2/lwjgl-openal-3.3.2.jar
  /home/ezntek/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-opengl/3.3.2/lwjgl-opengl-3.3.2.jar
  /home/ezntek/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-stb/3.3.2/lwjgl-stb-3.3.2.jar
  /home/ezntek/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-tinyfd/3.3.2/lwjgl-tinyfd-3.3.2.jar
  /home/ezntek/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl/3.3.2/lwjgl-3.3.2.jar
  /home/ezntek/.local/share/PrismLauncher/libraries/com/github/oshi/oshi-core/6.4.5/oshi-core-6.4.5.jar
  /home/ezntek/.local/share/PrismLauncher/libraries/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar
  /home/ezntek/.local/share/PrismLauncher/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  /home/ezntek/.local/share/PrismLauncher/libraries/com/google/guava/guava/32.1.2-jre/guava-32.1.2-jre.jar
  /home/ezntek/.local/share/PrismLauncher/libraries/com/ibm/icu/icu4j/73.2/icu4j-73.2.jar
  /home/ezntek/.local/share/PrismLauncher/libraries/com/mojang/authlib/6.0.52/authlib-6.0.52.jar
  /home/ezntek/.local/share/PrismLauncher/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  /home/ezntek/.local/share/PrismLauncher/libraries/com/mojang/brigadier/1.2.9/brigadier-1.2.9.jar
  /home/ezntek/.local/share/PrismLauncher/libraries/com/mojang/datafixerupper/6.0.8/datafixerupper-6.0.8.jar
  /home/ezntek/.local/share/PrismLauncher/libraries/com/mojang/logging/1.1.1/logging-1.1.1.jar
  /home/ezntek/.local/share/PrismLauncher/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  /home/ezntek/.local/share/PrismLauncher/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar
  /home/ezntek/.local/share/PrismLauncher/libraries/commons-codec/commons-codec/1.16.0/commons-codec-1.16.0.jar
  /home/ezntek/.local/share/PrismLauncher/libraries/commons-io/commons-io/2.13.0/commons-io-2.13.0.jar
  /home/ezntek/.local/share/PrismLauncher/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  /home/ezntek/.local/share/PrismLauncher/libraries/io/netty/netty-buffer/4.1.97.Final/netty-buffer-4.1.97.Final.jar
  /home/ezntek/.local/share/PrismLauncher/libraries/io/netty/netty-codec/4.1.97.Final/netty-codec-4.1.97.Final.jar
  /home/ezntek/.local/share/PrismLauncher/libraries/io/netty/netty-common/4.1.97.Final/netty-common-4.1.97.Final.jar
  /home/ezntek/.local/share/PrismLauncher/libraries/io/netty/netty-handler/4.1.97.Final/netty-handler-4.1.97.Final.jar
  /home/ezntek/.local/share/PrismLauncher/libraries/io/netty/netty-resolver/4.1.97.Final/netty-resolver-4.1.97.Final.jar
  /home/ezntek/.local/share/PrismLauncher/libraries/io/netty/netty-transport-classes-epoll/4.1.97.Final/netty-transport-classes-epoll-4.1.97.Final.jar
  /home/ezntek/.local/share/PrismLauncher/libraries/io/netty/netty-transport-native-unix-common/4.1.97.Final/netty-transport-native-unix-common-4.1.97.Final.jar
  /home/ezntek/.local/share/PrismLauncher/libraries/io/netty/netty-transport/4.1.97.Final/netty-transport-4.1.97.Final.jar
  /home/ezntek/.local/share/PrismLauncher/libraries/it/unimi/dsi/fastutil/8.5.12/fastutil-8.5.12.jar
  /home/ezntek/.local/share/PrismLauncher/libraries/net/java/dev/jna/jna-platform/5.13.0/jna-platform-5.13.0.jar
  /home/ezntek/.local/share/PrismLauncher/libraries/net/java/dev/jna/jna/5.13.0/jna-5.13.0.jar
  /home/ezntek/.local/share/PrismLauncher/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  /home/ezntek/.local/share/PrismLauncher/libraries/org/apache/commons/commons-compress/1.22/commons-compress-1.22.jar
  /home/ezntek/.local/share/PrismLauncher/libraries/org/apache/commons/commons-lang3/3.13.0/commons-lang3-3.13.0.jar
  /home/ezntek/.local/share/PrismLauncher/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  /home/ezntek/.local/share/PrismLauncher/libraries/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar
  /home/ezntek/.local/share/PrismLauncher/libraries/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar
  /home/ezntek/.local/share/PrismLauncher/libraries/org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar
  /home/ezntek/.local/share/PrismLauncher/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar
  /home/ezntek/.local/share/PrismLauncher/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar
  /home/ezntek/.local/share/PrismLauncher/libraries/org/slf4j/slf4j-api/2.0.7/slf4j-api-2.0.7.jar
  /home/ezntek/.local/share/PrismLauncher/libraries/com/mojang/minecraft/1.20.4/minecraft-1.20.4-client.jar

Native libraries:

Params:
  --username  --version 1.20.4 --gameDir /home/ezntek/.local/share/PrismLauncher/instances/1.20.4/.minecraft --assetsDir /home/ezntek/.local/share/PrismLauncher/assets --assetIndex 12 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Launcher: standard

Java Arguments:
[-Xms2048m, -Xmx16384m, -Duser.language=en]


Minecraft process ID: 78766


[14:59:58] [Datafixer Bootstrap/INFO]: 198 Datafixer optimizations took 222 milliseconds
[14:59:59] [main/WARN]: Unrecognized user type: offline
Exception caught from launcher
java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
	at ab.a(SourceFile:66)
	at evi.a(SourceFile:2605)
	at evi.a(SourceFile:2580)
	at net.minecraft.client.main.Main.main(SourceFile:233)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.LinkageError: Unknown platform: OpenBSD [in thread "Render thread"]
	at org.lwjgl.system.Platform.<clinit>(Platform.java:91)
	at org.lwjgl.system.Library.<clinit>(Library.java:33)
	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:100)
	at eoz.<clinit>(SourceFile:8)
	at epw.<init>(SourceFile:49)
	at eqd.<init>(SourceFile:33)
	at com.mojang.blaze3d.systems.RenderSystem.<clinit>(SourceFile:51)
	at net.minecraft.client.main.Main.main(SourceFile:220)
	... 3 more
Exiting with ERROR
Process exited with code 2.
```

The Meta API URL is empty, and i did try  "Download all".

**Comment by Octol1ttle** [comment]
Does this issue still happen on 11.0.2?
