### ISSUE TITLE
Fail to launch minecraft in wayland

### ISSUE THREAD

**Issue by drshapeless** [PrismLauncher/PrismLauncher#2298]
### Operating System

Gentoo Linux

### Version of Prism Launcher

Prism Launcher 8.2

### Version of Qt

Qt 5.15.13

### Description of bug

Cannot launch Minecraft, prism launcher is fine though

### Steps to reproduce

Add an unmodified 1.20.4 instance, click launch and nothing happen.

### Suspected cause

I suspect it to be some bug about glfw. However, I was playing it fine without changing anything yesterday. But I can no longer launch Minecraft today. 

I am using Gentoo, with a custom build glfw-wayland on my system. I have configured prism launcher to use system glfw.

Here is the error log. It does not even give me an error code. Just GLFW failed to initialize. 
```
---- Minecraft Crash Report ----
// Don't do that.

Time: 2024-04-11 23:43:52
Description: Initializing game

java.lang.ExceptionInInitializerError
	at org.lwjgl.glfw.GLFW.nglfwGetError(GLFW.java:1251)
	at org.lwjgl.glfw.GLFW.glfwGetError(GLFW.java:1280)
	at epf.a(SourceFile:136)
	at com.mojang.blaze3d.platform.GLX._initGlfw(SourceFile:66)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(SourceFile:848)
	at evi.<init>(SourceFile:512)
	at net.minecraft.client.main.Main.main(SourceFile:223)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.NullPointerException: A required function is missing: glfwInitAllocator
	at org.lwjgl.system.APIUtil.requiredFunctionMissing(APIUtil.java:145)
	at org.lwjgl.system.APIUtil.apiGetFunctionAddress(APIUtil.java:139)
	at org.lwjgl.glfw.GLFW$Functions.<clinit>(GLFW.java:42)
	... 10 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.lwjgl.glfw.GLFW.nglfwGetError(GLFW.java:1251)
	at org.lwjgl.glfw.GLFW.glfwGetError(GLFW.java:1280)
	at epf.a(SourceFile:136)
	at com.mojang.blaze3d.platform.GLX._initGlfw(SourceFile:66)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(SourceFile:848)
	at evi.<init>(SourceFile:512)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:223)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Linux (amd64) version 6.6.21-gentoo-dist
	Java Version: 17.0.10, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 133900736 bytes (127 MiB) / 536870912 bytes (512 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600 6-Core Processor
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: TU104 [GeForce RTX 2060]
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MB): 288.00
	Graphics card #0 deviceId: 0x1e89
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 7947.10
	Virtual memory used (MB): 3578.61
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xms512m -Xmx4096m
	Launched Version: 1.20.4
	Launcher name: PrismLauncher
	Backend library: LWJGL version 3.3.2+13
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Probably not. Client jar signature and brand is untouched
	Universe: 404
	Type: Client (map_client.txt)
	Locale: en_US
```

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by drshapeless** [comment]
This is fixed by uninstalling xwayland.
