### ISSUE TITLE
Can not run Minecraft 1.20.1 Forge

### ISSUE THREAD

**Issue by Minkx1** [PrismLauncher/PrismLauncher#2600]
This is my problem, I can't fix it and it in all my instances.

Checking: MC_SLIM
Checking: MERGED_MAPPINGS
Checking: MAPPINGS
Checking: MC_EXTRA
Checking: MOJMAPS
Checking: PATCHED
Checking: MC_SRG
2024-07-02 18:55:17,409 main WARN Advanced terminal features are not available in this environment
[18:55:17] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Minkx1, --version, 1.20.1, --gameDir, C:/Users/user/Desktop/Minecraft/Prism/instances/Forge RoBMbmo2/.minecraft, --assetsDir, C:/Users/user/Desktop/Minecraft/Prism/assets, --assetIndex, 5, --uuid, <ID ПРОФІЛЮ>, --accessToken, ????????, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 47.3.0, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412]
[18:55:17] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17.0.10 by Oracle Corporation; OS Windows 10 arch amd64 version 10.0
[18:55:17] [main/INFO] [ne.mi.fm.lo.ImmediateWindowHandler/]: Loading ImmediateWindowProvider fmlearlywindow
[18:55:17] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.6
[18:55:17] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.5
[18:55:17] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.4
[18:55:17] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.3
[18:55:17] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.2
[18:55:18] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.1
[18:55:18] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.0
[18:55:18] [main/INFO] [EARLYDISPLAY/]: Trying GL version 3.3
[18:55:18] [main/INFO] [EARLYDISPLAY/]: Trying GL version 3.2
[18:55:18] [main/ERROR] [EARLYDISPLAY/]: Failed to find any valid GLFW profile. Trying 4.6: GLFW error: [0x10006]WGL: The driver does not appear to support OpenGL
[18:55:18] [main/ERROR] [EARLYDISPLAY/]: ERROR DISPLAY
Failed to initialize graphics window with current settings.

Failure details:
Failed to find a valid GLFW profile.
We tried 4.6, 4.5, 4.4, 4.3, 4.2, 4.1, 4.0, 3.3, 3.2 but none of them worked.
Trying 4.6: GLFW error: [0x10006]WGL: The driver does not appear to support OpenGL
Trying 4.5: GLFW error: [0x10006]WGL: The driver does not appear to support OpenGL
Trying 4.4: GLFW error: [0x10006]WGL: The driver does not appear to support OpenGL
Trying 4.3: GLFW error: [0x10006]WGL: The driver does not appear to support OpenGL
Trying 4.2: GLFW error: [0x10006]WGL: The driver does not appear to support OpenGL
Trying 4.1: GLFW error: [0x10006]WGL: The driver does not appear to support OpenGL
Trying 4.0: GLFW error: [0x10006]WGL: The driver does not appear to support OpenGL
Trying 3.3: GLFW error: [0x10006]WGL: The driver does not appear to support OpenGL
Trying 3.2: GLFW error: [0x10006]WGL: The driver does not appear to support OpenGL

If you click yes, we will try and open https://links.minecraftforge.net/early-display-errors in your default browser
Exception caught from launcher
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.IllegalStateException: Failed to create a GLFW window with any profile
	at MC-BOOTSTRAP/fmlearlydisplay@1.20.1-47.3.0/net.minecraftforge.fml.earlydisplay.DisplayWindow.initWindow(DisplayWindow.java:426)
	at MC-BOOTSTRAP/fmlearlydisplay@1.20.1-47.3.0/net.minecraftforge.fml.earlydisplay.DisplayWindow.start(DisplayWindow.java:294)
	at MC-BOOTSTRAP/fmlearlydisplay@1.20.1-47.3.0/net.minecraftforge.fml.earlydisplay.DisplayWindow.initialize(DisplayWindow.java:157)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.0/net.minecraftforge.fml.loading.ImmediateWindowHandler.load(ImmediateWindowHandler.java:48)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.0/net.minecraftforge.fml.loading.ModDirTransformerDiscoverer.earlyInitialization(ModDirTransformerDiscoverer.java:43)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.lambda$discoverServices$18(TransformationServicesHandler.java:131)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.discoverServices(TransformationServicesHandler.java:131)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:87)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
	... 8 more
Exiting with ERROR
Процес завершився з кодом 2.

**Comment by Trial97** [comment]
The driver does not appear to support OpenGL

**Comment by Minkx1** [comment]
And how do I fix that?

**Comment by Trial97** [comment]
From the error message your video driver doesn't support opengl try updating them like mentioned in the url from logs

**Comment by Minkx1** [comment]
> From the error message your video driver doesn't support opengl try updating them like mentioned in the url from logs

For some reasone I can't open link. I just need to make my drivers support OpenGL?
