### ISSUE TITLE
java.net.ConnectException: Connection timed out

### ISSUE THREAD

**Issue by randompersononinternet69** [PrismLauncher/PrismLauncher#2601]
### Operating System

Windows 10 22H2

### Version of Prism Launcher

Prism Launcher 8.4

### Version of Qt

Qt 6.6.3

### Description of bug

Some strange error occurs early in the startup process of instances requiring Java 17 or later.
```
Prism Launcher version: 8.4 (official)


Launched instance in online mode

login.microsoftonline.com resolves to:
    [2603:1036:3000:e8::1, 2603:1036:3000:f8::3, 2603:1036:3000:e8::4, 2603:1036:3000:f0::2, 2603:1036:3000:f0::1, 2603:1036:3000:f8::1, 2603:1036:3000:f8::4, 2603:1036:3000:e8::2, 20.190.151.70, 20.190.151.133, 20.190.151.7, 20.190.151.6, 20.190.151.131, 20.190.151.134, 20.190.151.9, 20.190.151.69]

session.minecraft.net resolves to:
    [2620:1ec:bdf::40, 13.107.246.40]

textures.minecraft.net resolves to:
    [2620:1ec:29:1::40, 13.107.253.40]

api.mojang.com resolves to:
    [2620:1ec:bdf::40, 13.107.253.40]


Minecraft folder is:
C:/Users/tcffan123/AppData/Roaming/PrismLauncher/instances/1.19.4/.minecraft


Java path is:
C:/Program Files/Java/jdk-17/bin/javaw.exe


Java is version 17.0.11, using 64 (amd64) architecture, from Oracle Corporation.


Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/instances/1.19.4/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-glfw-natives-windows-arm64/3.3.1/lwjgl-glfw-natives-windows-arm64-3.3.1.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-glfw-natives-windows-x86/3.3.1/lwjgl-glfw-natives-windows-x86-3.3.1.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-glfw-natives-windows/3.3.1/lwjgl-glfw-natives-windows-3.3.1.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-jemalloc-natives-windows-arm64/3.3.1/lwjgl-jemalloc-natives-windows-arm64-3.3.1.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-jemalloc-natives-windows-x86/3.3.1/lwjgl-jemalloc-natives-windows-x86-3.3.1.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-jemalloc-natives-windows/3.3.1/lwjgl-jemalloc-natives-windows-3.3.1.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-natives-windows-arm64/3.3.1/lwjgl-natives-windows-arm64-3.3.1.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-natives-windows-x86/3.3.1/lwjgl-natives-windows-x86-3.3.1.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-natives-windows/3.3.1/lwjgl-natives-windows-3.3.1.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-openal-natives-windows-arm64/3.3.1/lwjgl-openal-natives-windows-arm64-3.3.1.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-openal-natives-windows-x86/3.3.1/lwjgl-openal-natives-windows-x86-3.3.1.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-openal-natives-windows/3.3.1/lwjgl-openal-natives-windows-3.3.1.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-opengl-natives-windows-arm64/3.3.1/lwjgl-opengl-natives-windows-arm64-3.3.1.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-opengl-natives-windows-x86/3.3.1/lwjgl-opengl-natives-windows-x86-3.3.1.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-opengl-natives-windows/3.3.1/lwjgl-opengl-natives-windows-3.3.1.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-stb-natives-windows-arm64/3.3.1/lwjgl-stb-natives-windows-arm64-3.3.1.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-stb-natives-windows-x86/3.3.1/lwjgl-stb-natives-windows-x86-3.3.1.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-stb-natives-windows/3.3.1/lwjgl-stb-natives-windows-3.3.1.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-tinyfd-natives-windows-arm64/3.3.1/lwjgl-tinyfd-natives-windows-arm64-3.3.1.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-tinyfd-natives-windows-x86/3.3.1/lwjgl-tinyfd-natives-windows-x86-3.3.1.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-tinyfd-natives-windows/3.3.1/lwjgl-tinyfd-natives-windows-3.3.1.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/com/github/oshi/oshi-core/6.2.2/oshi-core-6.2.2.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/com/google/code/gson/gson/2.10/gson-2.10.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/com/google/guava/guava/31.1-jre/guava-31.1-jre.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/com/ibm/icu/icu4j/71.1/icu4j-71.1.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/com/mojang/authlib/3.18.38/authlib-3.18.38.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/com/mojang/datafixerupper/6.0.6/datafixerupper-6.0.6.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/com/mojang/logging/1.1.1/logging-1.1.1.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/com/mojang/text2speech/1.16.7/text2speech-1.16.7.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/io/netty/netty-buffer/4.1.82.Final/netty-buffer-4.1.82.Final.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/io/netty/netty-codec/4.1.82.Final/netty-codec-4.1.82.Final.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/io/netty/netty-common/4.1.82.Final/netty-common-4.1.82.Final.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/io/netty/netty-handler/4.1.82.Final/netty-handler-4.1.82.Final.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/io/netty/netty-resolver/4.1.82.Final/netty-resolver-4.1.82.Final.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/io/netty/netty-transport-classes-epoll/4.1.82.Final/netty-transport-classes-epoll-4.1.82.Final.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/io/netty/netty-transport-native-unix-common/4.1.82.Final/netty-transport-native-unix-common-4.1.82.Final.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/io/netty/netty-transport/4.1.82.Final/netty-transport-4.1.82.Final.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/it/unimi/dsi/fastutil/8.5.9/fastutil-8.5.9.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/net/java/dev/jna/jna-platform/5.12.1/jna-platform-5.12.1.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/net/java/dev/jna/jna/5.12.1/jna-5.12.1.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/apache/httpcomponents/httpcore/4.4.15/httpcore-4.4.15.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/slf4j/slf4j-api/2.0.1/slf4j-api-2.0.1.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/io/github/zekerzhayard/ForgeWrapper/prism-2024-02-29/ForgeWrapper-prism-2024-02-29.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/cpw/mods/securejarhandler/2.1.6/securejarhandler-2.1.6.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/ow2/asm/asm/9.7/asm-9.7.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/ow2/asm/asm-commons/9.7/asm-commons-9.7.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/ow2/asm/asm-tree/9.7/asm-tree-9.7.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/ow2/asm/asm-util/9.7/asm-util-9.7.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/ow2/asm/asm-analysis/9.7/asm-analysis-9.7.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/net/minecraftforge/accesstransformers/8.0.4/accesstransformers-8.0.4.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/net/minecraftforge/eventbus/6.0.3/eventbus-6.0.3.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/net/minecraftforge/forgespi/6.0.0/forgespi-6.0.0.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/net/minecraftforge/coremods/5.0.1/coremods-5.0.1.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/cpw/mods/modlauncher/10.0.8/modlauncher-10.0.8.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/com/electronwill/night-config/core/3.6.4/core-3.6.4.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/com/electronwill/night-config/toml/3.6.4/toml-3.6.4.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/apache/maven/maven-artifact/3.8.5/maven-artifact-3.8.5.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/net/jodah/typetools/0.8.3/typetools-0.8.3.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/jline/jline-reader/3.12.1/jline-reader-3.12.1.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/jline/jline-terminal/3.12.1/jline-terminal-3.12.1.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/org/openjdk/nashorn/nashorn-core/15.3/nashorn-core-15.3.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/net/minecraftforge/JarJarSelector/0.3.19/JarJarSelector-0.3.19.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/net/minecraftforge/JarJarMetadata/0.3.19/JarJarMetadata-0.3.19.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/cpw/mods/bootstraplauncher/1.1.2/bootstraplauncher-1.1.2.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/net/minecraftforge/JarJarFileSystems/0.3.19/JarJarFileSystems-0.3.19.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/net/minecraftforge/fmlloader/1.19.4-45.3.0/fmlloader-1.19.4-45.3.0.jar
  C:/Users/tcffan123/AppData/Roaming/PrismLauncher/libraries/com/mojang/minecraft/1.19.4/minecraft-1.19.4-client.jar

Native libraries:

Mods:
  [✔] luckytntlib-1.19.4-45.2.15.0
  [✔] luckytntmod-1.19.4-1.4
  [✔] witherstormmod-1.19.4-3.4-all

Params:
  --username  --version 1.19.4 --gameDir C:/Users/tcffan123/AppData/Roaming/PrismLauncher/instances/1.19.4/.minecraft --assetsDir C:/Users/tcffan123/AppData/Roaming/PrismLauncher/assets --assetIndex 3 --uuid  --accessToken  --userType  --versionType release --launchTarget forgeclient --fml.forgeVersion 45.3.0 --fml.mcVersion 1.19.4 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20230314.122934

Window size: 854 x 480

Launcher: standard

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx4096m, -Duser.language=en]


Minecraft process ID: 20560


Checking: MC_SLIM
Missing: C:\Users\tcffan123\AppData\Roaming\PrismLauncher\libraries\net\minecraft\client\1.19.4-20230314.122934\client-1.19.4-20230314.122934-slim.jar
Some extra libraries are missing! Running the installer to generate them now.
JVM info: Oracle Corporation - 17.0.11 - 17.0.11+7-LTS-207
java.net.preferIPv4Stack=true
Created Temporary Directory: C:\Users\tcffan123\AppData\Local\Temp\forge_installer1554416155967149057
  Extracting: /data/client.lzma
Building Processors
===============================================================================
  MainClass: net.minecraftforge.installertools.ConsoleTool
  Classpath:
    C:\Users\tcffan123\AppData\Roaming\PrismLauncher\libraries\net\minecraftforge\installertools\1.4.1\installertools-1.4.1.jar
    C:\Users\tcffan123\AppData\Roaming\PrismLauncher\libraries\net\sf\jopt-simple\jopt-simple\6.0-alpha-3\jopt-simple-6.0-alpha-3.jar
    C:\Users\tcffan123\AppData\Roaming\PrismLauncher\libraries\com\google\code\gson\gson\2.10.1\gson-2.10.1.jar
    C:\Users\tcffan123\AppData\Roaming\PrismLauncher\libraries\de\siegmar\fastcsv\2.2.2\fastcsv-2.2.2.jar
    C:\Users\tcffan123\AppData\Roaming\PrismLauncher\libraries\net\minecraftforge\srgutils\0.5.6\srgutils-0.5.6.jar
    C:\Users\tcffan123\AppData\Roaming\PrismLauncher\libraries\org\ow2\asm\asm-commons\9.6\asm-commons-9.6.jar
    C:\Users\tcffan123\AppData\Roaming\PrismLauncher\libraries\org\ow2\asm\asm-tree\9.6\asm-tree-9.6.jar
    C:\Users\tcffan123\AppData\Roaming\PrismLauncher\libraries\org\ow2\asm\asm\9.6\asm-9.6.jar
  Args: --task, MCP_DATA, --input, C:\Users\tcffan123\AppData\Roaming\PrismLauncher\libraries\de\oceanlabs\mcp\mcp_config\1.19.4-20230314.122934\mcp_config-1.19.4-20230314.122934.zip, --output, C:\Users\tcffan123\AppData\Roaming\PrismLauncher\libraries\de\oceanlabs\mcp\mcp_config\1.19.4-20230314.122934\mcp_config-1.19.4-20230314.122934-mappings.txt, --key, mappings
Task: MCP_DATA
Input:  C:\Users\tcffan123\AppData\Roaming\PrismLauncher\libraries\de\oceanlabs\mcp\mcp_config\1.19.4-20230314.122934\mcp_config-1.19.4-20230314.122934.zip
Output: C:\Users\tcffan123\AppData\Roaming\PrismLauncher\libraries\de\oceanlabs\mcp\mcp_config\1.19.4-20230314.122934\mcp_config-1.19.4-20230314.122934-mappings.txt
Key:    mappings
Extracting: config/joined.tsrg
===============================================================================
  MainClass: net.minecraftforge.installertools.ConsoleTool
  Classpath:
    C:\Users\tcffan123\AppData\Roaming\PrismLauncher\libraries\net\minecraftforge\installertools\1.4.1\installertools-1.4.1.jar
    C:\Users\tcffan123\AppData\Roaming\PrismLauncher\libraries\net\sf\jopt-simple\jopt-simple\6.0-alpha-3\jopt-simple-6.0-alpha-3.jar
    C:\Users\tcffan123\AppData\Roaming\PrismLauncher\libraries\com\google\code\gson\gson\2.10.1\gson-2.10.1.jar
    C:\Users\tcffan123\AppData\Roaming\PrismLauncher\libraries\de\siegmar\fastcsv\2.2.2\fastcsv-2.2.2.jar
    C:\Users\tcffan123\AppData\Roaming\PrismLauncher\libraries\net\minecraftforge\srgutils\0.5.6\srgutils-0.5.6.jar
    C:\Users\tcffan123\AppData\Roaming\PrismLauncher\libraries\org\ow2\asm\asm-commons\9.6\asm-commons-9.6.jar
    C:\Users\tcffan123\AppData\Roaming\PrismLauncher\libraries\org\ow2\asm\asm-tree\9.6\asm-tree-9.6.jar
    C:\Users\tcffan123\AppData\Roaming\PrismLauncher\libraries\org\ow2\asm\asm\9.6\asm-9.6.jar
  Args: --task, DOWNLOAD_MOJMAPS, --version, 1.19.4, --side, client, --output, C:\Users\tcffan123\AppData\Roaming\PrismLauncher\libraries\net\minecraft\client\1.19.4-20230314.122934\client-1.19.4-20230314.122934-mappings.txt
Task: DOWNLOAD_MOJMAPS
MC Version: 1.19.4
Side:       client
Output:     C:\Users\tcffan123\AppData\Roaming\PrismLauncher\libraries\net\minecraft\client\1.19.4-20230314.122934\client-1.19.4-20230314.122934-mappings.txt
Sanitize:   false
Format:     TSRG
Skip:       false
java.net.ConnectException: Connection timed out: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:579)
	at java.base/sun.nio.ch.Net.connect(Net.java:568)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:593)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:534)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:639)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1687)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1611)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at java.base/java.net.URL.openStream(URL.java:1161)
	at net.minecraftforge.installertools.DownloadMojmaps.process(DownloadMojmaps.java:67)
	at net.minecraftforge.installertools.ConsoleTool.main(ConsoleTool.java:41)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.minecraftforge.installer.actions.PostProcessors.process(PostProcessors.java:219)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.github.zekerzhayard.forgewrapper.installer.util.InstallerV1.runClientInstall(InstallerV1.java:26)
	at io.github.zekerzhayard.forgewrapper.installer.Installer.install(Installer.java:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:59)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Failed to run processor: java.net.ConnectException:Connection timed out: connect
See log for more details
Failed to run processor: java.net.ConnectException:Connection timed out: connect
See log for more details.
Process exited with code 0.
Clipboard copy at: 02 Jul 2024 13:38:27 -0400
```

### Steps to reproduce

* Launch any instance requiring Java 17 or later
* Some Java "processor error" occurs

### Suspected cause

I have no idea

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
This is an issue with forge itself not prism: the forge installer tries to download some files and it fails.
Prism can't control that.
To make sure that you have the latest meta:
- delete `C:/Users/tcffan123/AppData/Roaming/PrismLauncher/meta`
- ensure `Metadata server` is empty in settings
- restart prism 

But again this is not a prism issue

**Comment by WxAaRoNxW** [comment]
apologies for replying on an old issues, but if any prismlauncher users are having issues or maybe even anyone who's stumbling upon this issue. I fixed it by adding the java argument.

```-Djava.net.preferIPv4Stack=true```

I then was able to remove the argument after the first launch. Leaving it on won't let you connect to ipv6 only servers.
