### ISSUE TITLE
A Bug

### ISSUE THREAD

**Issue by strongercape** [PrismLauncher/PrismLauncher#2676]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 8.4

### Version of Qt

8.4

### Description of bug

If I have a long command and want to correct something at the beginning, my game crashes with code 255 (Minecraft version: 1.21)

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2024-07-23 15:01:55
Description: keyPressed event handler

java.lang.StringIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
	at java.base/java.lang.String.checkIndex(Unknown Source)
	at java.base/java.lang.StringLatin1.charAt(Unknown Source)
	at java.base/java.lang.String.charAt(Unknown Source)
	at net.minecraft.class_4717.handler$zzj000$aoba$onRefresh(class_4717.java:569)
	at net.minecraft.class_4717.method_23934(class_4717.java:202)
	at net.minecraft.class_408.method_23945(class_408.java:85)
	at net.minecraft.class_342.method_1874(class_342.java:154)
	at net.minecraft.class_342.method_1883(class_342.java:262)
	at net.minecraft.class_342.method_1855(class_342.java:248)
	at net.minecraft.class_342.method_25404(class_342.java:289)
	at net.minecraft.class_4069.method_25404(class_4069.java:80)
	at net.minecraft.class_437.method_25404(class_437.java:138)
	at net.minecraft.class_408.method_25404(class_408.java:95)
	at net.minecraft.class_309.method_1454(class_309.java:414)
	at net.minecraft.class_437.method_25412(class_437.java:431)
	at net.minecraft.class_309.method_1466(class_309.java:410)
	at net.minecraft.class_309.method_22678(class_309.java:499)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_309.method_22676(class_309.java:499)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:161)
	at net.minecraft.class_1041.method_15998(class_1041.java:303)
	at net.minecraft.class_310.method_1523(class_310.java:1307)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
	at java.base/java.lang.String.checkIndex(Unknown Source)
	at java.base/java.lang.StringLatin1.charAt(Unknown Source)
	at java.base/java.lang.String.charAt(Unknown Source)
	at net.minecraft.class_4717.handler$zzj000$aoba$onRefresh(class_4717.java:569)
	at net.minecraft.class_4717.method_23934(class_4717.java:202)
	at net.minecraft.class_408.method_23945(class_408.java:85)
	at net.minecraft.class_342.method_1874(class_342.java:154)
	at net.minecraft.class_342.method_1883(class_342.java:262)
	at net.minecraft.class_342.method_1855(class_342.java:248)
	at net.minecraft.class_342.method_25404(class_342.java:289)
	at net.minecraft.class_4069.method_25404(class_4069.java:80)
	at net.minecraft.class_437.method_25404(class_437.java:138)
	at net.minecraft.class_408.method_25404(class_408.java:95)
	at net.minecraft.class_309.method_1454(class_309.java:414)
	at net.minecraft.class_437.method_25412(class_437.java:431)
	at net.minecraft.class_309.method_1466(class_309.java:410)
	at net.minecraft.class_309.method_22678(class_309.java:499)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_309.method_22676(class_309.java:499)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:161)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_408
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:431)
	at net.minecraft.class_309.method_1466(class_309.java:410)
	at net.minecraft.class_309.method_22678(class_309.java:499)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_309.method_22676(class_309.java:499)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:161)
	at net.minecraft.class_1041.method_15998(class_1041.java:303)
	at net.minecraft.class_310.method_1523(class_310.java:1307)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Uptime --
Details:
	JVM uptime: 538.679s
	Wall uptime: 519.037s
	High-res time: 516.775s
	Client ticks: 10145 ticks / 507.250s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2501)
	at net.minecraft.class_310.method_54580(class_310.java:949)
	at net.minecraft.class_310.method_1514(class_310.java:902)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Affected level --
Details:
	All players: 8 total; [class_746['StrongerCape'/301, l='ClientLevel', x=-980.67, y=76.78, z=-1103.80], class_745['Â§3Â§fÂ§dÂ§aÂ§fÂ§5Â§lÂ§6'/71, l='ClientLevel', x=-984.98, y=70.00, z=-1115.34], class_745['Â§bÂ§7Â§bÂ§7Â§6Â§2Â§eÂ§c'/70, l='ClientLevel', x=-985.20, y=70.00, z=-1117.66], class_745['Â§1Â§fÂ§5Â§lÂ§eÂ§4Â§fÂ§b'/72, l='ClientLevel', x=-985.47, y=70.00, z=-1119.67], class_745['Â§oÂ§4Â§oÂ§cÂ§aÂ§kÂ§4Â§3'/69, l='ClientLevel', x=-992.81, y=70.00, z=-1117.68], class_745['Â§0Â§fÂ§0Â§8Â§1Â§oÂ§0Â§d'/67, l='ClientLevel', x=-988.21, y=70.00, z=-1117.51], class_745['Â§eÂ§2Â§lÂ§1Â§lÂ§bÂ§8Â§6'/68, l='ClientLevel', x=-988.63, y=70.00, z=-1116.00], class_745['Â§lÂ§2Â§cÂ§mÂ§2Â§nÂ§8Â§d'/66, l='ClientLevel', x=-988.64, y=70.00, z=-1119.15]]
	Chunk stats: 729, 453
	Level dimension: minecraft:overworld
	Level spawn location: World: (-987,70,-1116), Section: (at 5,6,4 in -62,4,-70; chunk contains blocks -992,-64,-1120 to -977,319,-1105), Region: (-2,-3; contains chunks -64,-96 to -33,-65, blocks -1024,-64,-1536 to -513,319,-1025)
	Level time: 2036831 game time, 78173 day time
	Server brand: Paper
	Server type: Non-integrated multiplayer server
	Tracked entity count: 142

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, aoba, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, file/ĂÂ§6DynamicĂÂ§9Surroundings ĂÂ§2R3.zip, file/better-sand-e2891.zip

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Linux (aarch64) version 6.6.31+rpt-rpi-v8
	Java Version: 21.0.3, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 4554237056 bytes (4343 MiB) / 6576668672 bytes (6272 MiB) up to 7381975040 bytes (7040 MiB)
	CPUs: 4
	Processor Vendor: ARM
	Processor Name: Raspberry Pi 5 Model B Rev 1.0�
	Identifier: ARM Family 8 Model Raspberry Pi 5 Model B Rev 1.0 Stepping r4p1
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MiB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MiB): 35735.29
	Virtual memory used (MiB): 9786.58
	Swap memory total (MiB): 31764.70
	Swap memory used (MiB): 2129.75
	Space in storage for jna.tmpdir (MiB): <path not set>
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
	Space in storage for io.netty.native.workdir (MiB): <path not set>
	Space in storage for java.io.tmpdir (MiB): available: 63248.30, total: 119411.60
	Space in storage for workdir (MiB): available: 63248.30, total: 119411.60
	JVM Flags: 2 total; -Xms6272m -Xmx7040m
	Fabric Mods: 
		aoba: Aoba Hacked Client 1.4.2
		fabric-api: Fabric API 0.100.6+1.21
			fabric-api-base: Fabric API Base 0.4.42+6573ed8cd1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.67+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.28+6fc22b99d1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a7d1
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366fd1
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd9d1
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.14+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.17+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.4.1+86024ea6d1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.24+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.11+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.10+e633f883d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd9d1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.2+78017270d1
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a7d1
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b3d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.11+8f3583aed1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.12+3f89f5a5d1
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.0+3f89f5a5d1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6bd1
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.0+ab7edbacd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.12+d1321076d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.10+65089712d1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.24+6ced4dd9d1
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.3.0+0ae0b97dd1
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.6.5+48fb1586d1
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.67+df3654b3d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.70+df3654b3d1
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.4+5a8c785ed1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.2.1+d153f344d1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.1.5+78017270d1
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b5597344d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.81+b5597344d1
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8cd1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.15+3dccd343d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.12+6573ed8cd1
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		java: OpenJDK 64-Bit Server VM 21
		minecraft: Minecraft 1.21
	Launched Version: 1.21
	Launcher name: PrismLauncher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: V3D 7.1 GL version 3.3 (Core Profile) Mesa 23.2.1-1~bpo12+rpt3, Broadcom
	Window size: 1920x1012
	GFLW Platform: x11
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Render Distance: 10/12 chunks
	Resource Packs: vanilla, fabric, aoba, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, file/ĂÂ§6DynamicĂÂ§9Surroundings ĂÂ§2R3.zip, file/better-sand-e2891.zip (incompatible)
	Current Language: de_de
	Locale: en_DE
	System encoding: ISO-8859-1
	File encoding: UTF-8
	CPU: 4x Raspberry Pi 5 Model B Rev 1.0

### Steps to reproduce

...............

### Suspected cause

no

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Thank you for bringing this to our attention. After reviewing the details, we have determined that this issue is unrelated to the launcher. If you need any more help with this kind of issue, we recommend contacting our community on Discord:https://prismlauncher.org/discord.

We appreciate your understanding and cooperation.
