### ISSUE TITLE
Minecraft narrator not available on Flatpak version of Prism

### ISSUE THREAD

**Issue by Meatwo310** [PrismLauncher/PrismLauncher#2683]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 8.4

### Version of Qt

Qt 6.7.2

### Description of bug

Minecraft should provide the narrator feature using the system's `flite` shared library, but it does not, even with `flite` installed, on the Flatpak version of Prism.

![image](https://github.com/user-attachments/assets/7a29fbb9-ba2d-4eec-8d2a-f2d8527981c9)

The [AUR version](https://aur.archlinux.org/packages/prismlauncher) and the AppImage version work fine after I installed the [`flite`](https://archlinux.org/packages/extra/x86_64/flite/) package, but the Flatpak version does not work and says `Failed to load library flite`. 

I have tried to set `filesystem=host` with Flatseal, but nothing happened.

Here is a log of running vanilla Minecraft 1.21 on EndeavourOS using the Flatpak version of Prism: [mclo.gs](https://mclo.gs/jn9KB25) | [GitHub Gist](https://gist.github.com/Meatwo310/610c18ab60326e6421a29258c6d2ba2b)
```log
[14:43:23] [Render thread/ERROR]: Error while loading the narrator
com.mojang.text2speech.Narrator$InitializeException: Failed to load library flite
	at com.mojang.text2speech.NarratorLinux$FliteLibrary.loadNative(NarratorLinux.java:69) ~[text2speech-1.17.9.jar:?]
	at com.mojang.text2speech.NarratorLinux.<init>(NarratorLinux.java:18) ~[text2speech-1.17.9.jar:?]
	at com.mojang.text2speech.Narrator.getNarrator(Narrator.java:41) [text2speech-1.17.9.jar:?]
	...
Caused by: java.lang.UnsatisfiedLinkError: Unable to load library 'flite':
libflite.so: 共有オブジェクトファイルを開けません: そのようなファイルやディレクトリはありません
...
```
(`共有オブジェクトファイルを開けません: そのようなファイルやディレクトリはありません` means `cannot open shared object file: No such file or directory`)

### Steps to reproduce

1. Install [`flite`](https://archlinux.org/packages/extra/x86_64/flatpak/) and [`flatpak`](https://archlinux.org/packages/extra/x86_64/flatpak/) from Arch repo or something
2. Install `org.prismlauncher.PrismLauncher` from Flathub
3. Run Prism and launch Vanilla Minecraft 1.21 (or older?)
4. See logs and `Settings` -> `Accessibility Settings...` -> `Narrator`

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by audaki** [comment]
I can confirm this bug exists on Flatpak version of Prism Launcher on Fedora 40 KDE

**Comment by Mephodio** [comment]
This worked for me:

```
# Obtain libflite. I installed it from package manager
sudo dnf install flite-devel-2.2-8.fc40.x86_64

# Copy libraries to a directory accessible from flatpak
mkdir -p /home/user/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/libflite
cp /usr/lib64/libflite* /home/user/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/libflite/

# Add this directory to library path for prism flatpak
flatpak override --user --env=LD_LIBRARY_PATH=/home/user/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/libflite org.prismlauncher.PrismLauncher
```

**Comment by FlamingSharky** [comment]
I don't mean to necropost but this has yet to find a fix for this as it still is happening to me. I'm on EndeavorOS and can't get it to work. By chance, seems to be happening similarly to my intelliJ install for minecraft mod development.

**Comment by Meatwo310** [comment]
Arch and EndeavourOS users can avoid this issue by installing [`prismlauncher`](https://archlinux.org/packages/extra/x86_64/prismlauncher/) or [`prismlauncher-git`](https://aur.archlinux.org/packages/prismlauncher-git) directly via pacman.

Users of other distributions can install Prism Launcher through their package manager via the community repository, which should allow them to use the system-installed flite.

However, when using the Flatpak version of Prism Launcher, we need to manually copy the flite libraries into the Flatpak directory and override the environment variable in order to get the narrator working.

I'm not sure if this is the ideal approach given how Flatpak works, but it would be great if flite could be included in the Flatpak build of Prism Launcher so users can use the narrator out of the box.

**Comment by Ryex** [comment]
@FlamingSharky @Meatwo310 
I've prepped a fix in the flatpack repo I'll post again when the build finished to ask you to test it.

EDIT:

please try the test build

https://github.com/flathub/org.prismlauncher.PrismLauncher/pull/91#issuecomment-2786264127

> Build [192314 successful](https://buildbot.flathub.org/#/builders/6/builds/192314) To test this build, install it from the testing repository:
> 
> ```
> flatpak install --user https://dl.flathub.org/build-repo/175600/org.prismlauncher.PrismLauncher.flatpakref
> ```

**Comment by Meatwo310** [comment]
@Ryex It works perfectly

![Image](https://github.com/user-attachments/assets/29eed6f1-674a-418d-b8a0-5a33991bca65)

**Comment by Ryex** [comment]
@getchoo  any way you can think of to test if this breaks for people not running pipewire?

**Comment by alexytomi** [comment]
@Meatwo310 Am on EndeavourOS, I am unable to get narrator working at all. It does not search `/usr/lib` nor whatever I define as `java.library.path` or `jna.library.path`.

**Comment by RangerMauve** [comment]
Getting this in the arch `prismlauncher` package. Not clear where I can copy the library since it isn't searching in `/usr/lib/`
