### ISSUE TITLE
I can't launch the game

### ISSUE THREAD

**Issue by nyxar77** [PrismLauncher/PrismLauncher#2856]
### Operating System

Linux

### Version of Prism Launcher

Prism launcher 8.3

### Version of Qt

Qt version 6.7.1

### Description of bug

none of the games won't launch I tried new instances too and the issue is still present

### Steps to reproduce

-- empty --

### Suspected cause

I don't know but I have this crash report that might be helpful:
```
Prism Launcher version: 8.3 (nixpkgs)


Launched instance in online mode

authserver.mojang.com resolves to:
    [N/A]

session.minecraft.net resolves to:
    [13.107.246.43, 2620:1ec:bdf::43]

textures.minecraft.net resolves to:
    [13.107.246.43, 2620:1ec:bdf::43]

api.mojang.com resolves to:
    [13.107.246.43, 2620:1ec:bdf::43]


Minecraft folder is:
/home/nyxar/.local/share/PrismLauncher/instances/1.21.1/.minecraft


Java path is:
/nix/store/sziqmjk1i28cxcr5x29jbz3dzhiz1pii-openjdk-headless-21+35/bin/java


Java is version 21, using 64 (amd64) architecture, from N/A.


AMD Ryzen 5 5500U with Radeon Graphics
Main Class:
  net.fabricmc.loader.impl.launch.knot.KnotClient

Native path:
  /home/nyxar/.local/share/PrismLauncher/instances/1.21.1/natives

Traits:
traits feature:is_quick_play_multiplayer
traits feature:is_quick_play_singleplayer
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  /home/nyxar/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-freetype-natives-linux/3.3.3/lwjgl-freetype-natives-linux-3.3.3.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-freetype/3.3.3/lwjgl-freetype-3.3.3.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-glfw-natives-linux/3.3.3/lwjgl-glfw-natives-linux-3.3.3.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-glfw/3.3.3/lwjgl-glfw-3.3.3.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-jemalloc-natives-linux/3.3.3/lwjgl-jemalloc-natives-linux-3.3.3.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-jemalloc/3.3.3/lwjgl-jemalloc-3.3.3.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-natives-linux/3.3.3/lwjgl-natives-linux-3.3.3.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-openal-natives-linux/3.3.3/lwjgl-openal-natives-linux-3.3.3.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-openal/3.3.3/lwjgl-openal-3.3.3.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-opengl-natives-linux/3.3.3/lwjgl-opengl-natives-linux-3.3.3.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-opengl/3.3.3/lwjgl-opengl-3.3.3.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-stb-natives-linux/3.3.3/lwjgl-stb-natives-linux-3.3.3.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-stb/3.3.3/lwjgl-stb-3.3.3.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-tinyfd-natives-linux/3.3.3/lwjgl-tinyfd-natives-linux-3.3.3.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-tinyfd/3.3.3/lwjgl-tinyfd-3.3.3.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl/3.3.3/lwjgl-3.3.3.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/com/github/oshi/oshi-core/6.4.10/oshi-core-6.4.10.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/com/google/guava/guava/32.1.2-jre/guava-32.1.2-jre.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/com/ibm/icu/icu4j/73.2/icu4j-73.2.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/com/mojang/authlib/6.0.54/authlib-6.0.54.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/com/mojang/brigadier/1.3.10/brigadier-1.3.10.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/com/mojang/datafixerupper/8.0.16/datafixerupper-8.0.16.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/com/mojang/logging/1.2.7/logging-1.2.7.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/commons-codec/commons-codec/1.16.0/commons-codec-1.16.0.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/commons-io/commons-io/2.15.1/commons-io-2.15.1.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/io/netty/netty-buffer/4.1.97.Final/netty-buffer-4.1.97.Final.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/io/netty/netty-codec/4.1.97.Final/netty-codec-4.1.97.Final.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/io/netty/netty-common/4.1.97.Final/netty-common-4.1.97.Final.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/io/netty/netty-handler/4.1.97.Final/netty-handler-4.1.97.Final.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/io/netty/netty-resolver/4.1.97.Final/netty-resolver-4.1.97.Final.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/io/netty/netty-transport-classes-epoll/4.1.97.Final/netty-transport-classes-epoll-4.1.97.Final.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/io/netty/netty-transport-native-epoll/4.1.97.Final/netty-transport-native-epoll-4.1.97.Final-linux-aarch_64.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/io/netty/netty-transport-native-epoll/4.1.97.Final/netty-transport-native-epoll-4.1.97.Final-linux-x86_64.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/io/netty/netty-transport-native-unix-common/4.1.97.Final/netty-transport-native-unix-common-4.1.97.Final.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/io/netty/netty-transport/4.1.97.Final/netty-transport-4.1.97.Final.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/it/unimi/dsi/fastutil/8.5.12/fastutil-8.5.12.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/net/java/dev/jna/jna-platform/5.14.0/jna-platform-5.14.0.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/net/java/dev/jna/jna/5.14.0/jna-5.14.0.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/org/apache/commons/commons-compress/1.26.0/commons-compress-1.26.0.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/org/apache/commons/commons-lang3/3.14.0/commons-lang3-3.14.0.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/org/apache/logging/log4j/log4j-api/2.22.1/log4j-api-2.22.1.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/org/apache/logging/log4j/log4j-core/2.22.1/log4j-core-2.22.1.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.22.1/log4j-slf4j2-impl-2.22.1.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/org/jcraft/jorbis/0.0.17/jorbis-0.0.17.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/org/lz4/lz4-java/1.8.0/lz4-java-1.8.0.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/org/slf4j/slf4j-api/2.0.9/slf4j-api-2.0.9.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/net/fabricmc/intermediary/1.21.1/intermediary-1.21.1.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/org/ow2/asm/asm/9.6/asm-9.6.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/org/ow2/asm/asm-analysis/9.6/asm-analysis-9.6.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/org/ow2/asm/asm-commons/9.6/asm-commons-9.6.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/org/ow2/asm/asm-tree/9.6/asm-tree-9.6.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/org/ow2/asm/asm-util/9.6/asm-util-9.6.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/net/fabricmc/sponge-mixin/0.15.3+mixin.0.8.7/sponge-mixin-0.15.3+mixin.0.8.7.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/net/fabricmc/fabric-loader/0.16.5/fabric-loader-0.16.5.jar
  /home/nyxar/.local/share/PrismLauncher/libraries/com/mojang/minecraft/1.21.1/minecraft-1.21.1-client.jar

Native libraries:

Mods:
  [✘] bclib-21.0.13.jar (disabled)
  [✘] better-end-21.0.11.jar (disabled)
  [✘] BetterF3-11.0.2-Fabric-1.21.1.jar (disabled)
  [✘] BridgingMod-2.4.0+1.21.fabric-release.jar (disabled)
  [✘] c2me-fabric-mc1.21.1-0.3.0+alpha.0.212.jar (disabled)
  [✘] cherishedworlds-fabric-10.0.2+1.21.1.jar (disabled)
  [✘] cloth-config-15.0.140-fabric.jar (disabled)
  [✘] connectiblechains-2.4.2+1.21.1.jar (disabled)
  [✘] cristellib-fabric-1.2.8.jar (disabled)
  [✘] DiagonalFences-v21.1.0-1.21.1-Fabric.jar (disabled)
  [✘] DiagonalWalls-v21.1.0-1.21.1-Fabric.jar (disabled)
  [✘] DiagonalWindows-v21.1.0-1.21.1-Fabric.jar (disabled)
  [✘] dungeons-and-taverns-4.4.jar (disabled)
  [✘] entityculling-fabric-1.7.0-mc1.21.jar (disabled)
  [✘] fabric-api-0.104.0+1.21.1.jar (disabled)
  [✘] ForgeConfigAPIPort-v21.1.0-1.21.1-Fabric.jar (disabled)
  [✘] fpsdisplay-4.2.1+1.21.1.jar (disabled)
  [✘] ImmersiveThunder-1.21.1+1.2.2.jar (disabled)
  [✘] iris-fabric-1.8.0-beta.4+mc1.21.1.jar (disabled)
  [✘] lightweight-inventory-sorting-1.1.2+1.21.jar (disabled)
  [✘] lithium-fabric-mc1.21.1-0.13.1.jar (disabled)
  [✘] modmenu-11.0.2.jar (disabled)
  [✘] MouseTweaks-fabric-mc1.21-2.26.jar (disabled)
  [✘] noisium-fabric-2.3.0+mc1.21-1.21.1.jar (disabled)
  [✘] placeholder-api-2.4.1+1.21.jar (disabled)
  [✘] PresenceFootsteps-1.10.0+1.21.jar (disabled)
  [✘] presencium-2.2.jar (disabled)
  [✘] PuzzlesLib-v21.1.10-1.21.1-Fabric.jar (disabled)
  [✘] sodium-fabric-0.6.0-beta.2+mc1.21.1.jar (disabled)
  [✘] Timer For Speedruns 1.2v 21+.jar (disabled)
  [✘] WI-Zoom-1.5-MC1.21.1.jar (disabled)

Params:
  --username  --version 1.21.1 --gameDir /home/nyxar/.local/share/PrismLauncher/instances/1.21.1/.minecraft --assetsDir /home/nyxar/.local/share/PrismLauncher/assets --assetIndex 17 --uuid  --accessToken  --userType  --versionType release

Window size: max (if available)

Launcher: standard

Java Arguments:
[-Xms512m, -Xmx4096m, -Duser.language=en]


Minecraft process ID: 2731


[08:10:31] [main/INFO]: Loading Minecraft 1.21.1 with Fabric Loader 0.16.5
[08:10:31] [main/INFO]: Loading 4 mods:
	- fabricloader 0.16.5
	   \-- mixinextras 0.4.1
	- java 21
	- minecraft 1.21.1
[08:10:31] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.7 Source=file:/home/nyxar/.local/share/PrismLauncher/libraries/net/fabricmc/sponge-mixin/0.15.3+mixin.0.8.7/sponge-mixin-0.15.3+mixin.0.8.7.jar Service=Knot/Fabric Env=CLIENT
[08:10:32] [main/WARN]: Did not find udev library in operating system. Some features may not work.
[08:10:32] [Datafixer Bootstrap/INFO]: 226 Datafixer optimizations took 289 milliseconds
[08:10:36] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[08:10:36] [Render thread/INFO]: Setting user: Nyxar77
[08:10:36] [Render thread/INFO]: Backend library: LWJGL version 3.3.3-snapshot
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2024-09-24 08:10:36
Description: Initializing game

java.lang.IllegalStateException: Failed to initialize GLFW, errors: GLFW error during init: [0x1000E]Failed to detect any supported platform
	at com.mojang.blaze3d.platform.GLX._initGlfw(GLX.java:77)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(RenderSystem.java:509)
	at net.minecraft.class_310.<init>(class_310.java:502)
	at net.minecraft.client.main.Main.main(Main.java:239)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.mojang.blaze3d.platform.GLX._initGlfw(GLX.java:77)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(RenderSystem.java:509)
	at net.minecraft.class_310.<init>(class_310.java:502)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:239)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Linux (amd64) version 6.6.32
	Java Version: 21, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 344256056 bytes (328 MiB) / 536870912 bytes (512 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5500U with Radeon Graphics
	Identifier: AuthenticAMD Family 23 Model 104 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MiB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MiB): 24041.55
	Virtual memory used (MiB): 2158.96
	Swap memory total (MiB): 16384.00
	Swap memory used (MiB): 0.00
	Space in storage for jna.tmpdir (MiB): <path not set>
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
	Space in storage for io.netty.native.workdir (MiB): <path not set>
	Space in storage for java.io.tmpdir (MiB): available: 6890.30, total: 8900.46
	Space in storage for workdir (MiB): available: 213460.17, total: 351502.47
	JVM Flags: 2 total; -Xms512m -Xmx4096m
	Launched Version: 1.21.1
	Launcher name: PrismLauncher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: Unknown
	Window size: <not initialized>
	GFLW Platform: <error>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 404
	Type: Client (map_client.txt)
	Locale: en_US
	System encoding: UTF-8
	File encoding: UTF-8
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# /home/nyxar/.local/share/PrismLauncher/instances/1.21.1/.minecraft/crash-reports/crash-2024-09-24_08.10.36-client.txt
Process exited with code 255.
```

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
Not a launcher issue

**Comment by nyxar77** [comment]
> Not a launcher issue

what is the solution then?

**Comment by Trial97** [comment]
As it is not related to the launcher I don't know.
