### ISSUE TITLE
ResourceModel_test.cpp seg faults

### ISSUE THREAD

**Issue by Trial97** [PrismLauncher/PrismLauncher#2927]
### Operating System

somehow it works on windows GH actions

### Description of bug

The ResourceModel_test segfaults and due to https://github.com/PrismLauncher/PrismLauncher/issues/2926 was not reported.

### Steps to reproduce

ctest -E "^example64|example$" --test-dir build --output-on-failure

### Suspected cause

there are two(right now):
1.  launcher/net/NetJob.cpp (solution: replace `#if defined(LAUNCHER_APPLICATION)` with `#if defined(LAUNCHER_APPLICATION) && !defined(LAUNCHER_TEST)`)
2. ResourceModel.cpp:332 somehow we try to access `APPLICATION->metacache()` that is not initialized(more exactly APPLICATION should not be init because it is a test)

here is the full stack trace for this one:
```
#0  0x00005555557781ae in std::_Rb_tree<QString, std::pair<QString const, HttpMetaCache::EntryMap>, std::_Select1st<std::pair<QString const, HttpMetaCache::EntryMap> >, std::less<QString>, std::allocator<std::pair<QString const, HttpMetaCache::EntryMap> > >::_M_begin (this=0x3cba1a7401001c1a) at /usr/include/c++/14.2.1/bits/stl_tree.h:743
#1  0x0000555555776f65 in std::_Rb_tree<QString, std::pair<QString const, HttpMetaCache::EntryMap>, std::_Select1st<std::pair<QString const, HttpMetaCache::EntryMap> >, std::less<QString>, std::allocator<std::pair<QString const, HttpMetaCache::EntryMap> > >::find (this=0x3cba1a7401001c1a, __k=...) at /usr/include/c++/14.2.1/bits/stl_tree.h:2541
#2  0x0000555555776335 in std::map<QString, HttpMetaCache::EntryMap, std::less<QString>, std::allocator<std::pair<QString const, HttpMetaCache::EntryMap> > >::find (this=0x3cba1a7401001c1a, __x=...)
    at /usr/include/c++/14.2.1/bits/stl_map.h:1244
#3  0x0000555555775620 in QMap<QString, HttpMetaCache::EntryMap>::contains (this=0x7ffff5e34e18 <__libc_start_call_main+136>, key=...) at /usr/include/qt6/QtCore/qmap.h:346
#4  0x000055555576ef3f in HttpMetaCache::getEntry (this=0x7ffff5e34e08 <__libc_start_call_main+120>, base=..., resource_path=...) at /home/user/Projects/PrismLauncher/launcher/net/HttpMetaCache.cpp:72
#5  0x000055555576f0bc in HttpMetaCache::resolveEntry (this=0x7ffff5e34e08 <__libc_start_call_main+120>, base=..., resource_path=..., expected_etag=...) at /home/user/Projects/PrismLauncher/launcher/net/HttpMetaCache.cpp:88
#6  0x0000555555c410b9 in ResourceDownload::ResourceModel::getIcon (this=0x7fffffffd550, index=..., url=...) at /home/user/Projects/PrismLauncher/launcher/ui/pages/modplatform/ResourceModel.cpp:332
#7  0x0000555555c3e9d9 in ResourceDownload::ResourceModel::data (this=0x7fffffffd550, index=..., role=1) at /home/user/Projects/PrismLauncher/launcher/ui/pages/modplatform/ResourceModel.cpp:63
#8  0x00007ffff7f5cdd2 in QAbstractItemModelTesterPrivate::testDataGuiRoles (this=0x5555562ba150, tester=<optimized out>) at /usr/src/debug/qt6-base/qtbase/src/testlib/qabstractitemmodeltester.cpp:646
#9  QAbstractItemModelTesterPrivate::data (this=this@entry=0x5555562ba150) at /usr/src/debug/qt6-base/qtbase/src/testlib/qabstractitemmodeltester.cpp:721
#10 0x00007ffff7f5e6a8 in QAbstractItemModelTesterPrivate::runAllTests (this=0x5555562ba150) at /usr/src/debug/qt6-base/qtbase/src/testlib/qabstractitemmodeltester.cpp:357
#11 QAbstractItemModelTesterPrivate::runAllTests (this=0x5555562ba150) at /usr/src/debug/qt6-base/qtbase/src/testlib/qabstractitemmodeltester.cpp:348
#12 operator() (__closure=<synthetic pointer>) at /usr/src/debug/qt6-base/qtbase/src/testlib/qabstractitemmodeltester.cpp:219
#13 QAbstractItemModelTester::QAbstractItemModelTester (this=<optimized out>, model=<optimized out>, mode=<optimized out>, parent=<optimized out>, this=<optimized out>, model=<optimized out>, mode=<optimized out>, parent=<optimized out>)
    at /usr/src/debug/qt6-base/qtbase/src/testlib/qabstractitemmodeltester.cpp:298
#14 0x000055555563f1e3 in ResourceModelTest::test_abstract_item_model (this=0x7fffffffdf30) at /home/user/Projects/PrismLauncher/tests/ResourceModel_test.cpp:65
#15 0x000055555563b7f8 in ResourceModelTest::qt_static_metacall (_o=0x7fffffffdf30, _c=QMetaObject::InvokeMetaMethod, _id=0, _a=0x7fffffffd930)
    at /home/user/Projects/PrismLauncher/build/tests/ResourceModel_autogen/include/ResourceModel_test.moc:161
--Type <RET> for more, q to quit, c to continue without paging--
#16 0x00007ffff656d0a5 in QMetaMethodInvoker::invokeImpl (self=..., target=<optimized out>, connectionType=connectionType@entry=Qt::DirectConnection, paramCount=paramCount@entry=1, parameters=parameters@entry=0x7fffffffd930,
    typeNames=0x7fffffffd938, metaTypes=0x7fffffffd940) at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qmetaobject.cpp:2755
#17 0x00007ffff656d3ef in QMetaMethod::invokeImpl (self=..., target=<optimized out>, connectionType=connectionType@entry=Qt::DirectConnection, paramCount=paramCount@entry=1, parameters=parameters@entry=0x7fffffffd930,
    typeNames=0x7fffffffd938, metaTypes=0x7fffffffd940) at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qmetaobject.cpp:2593
#18 0x00007ffff7f4184f in QMetaMethod::invoke<void> (c=Qt::DirectConnection, this=<synthetic pointer>, obj=<optimized out>, r=...) at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qmetaobject.h:149
#19 QMetaMethod::invoke<>(QObject*, Qt::ConnectionType) const (c=Qt::DirectConnection, this=<synthetic pointer>, obj=<optimized out>) at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qmetaobject.h:161
#20 QTest::invokeTestMethodIfValid (m=..., obj=<optimized out>) at /usr/src/debug/qt6-base/qtbase/src/testlib/qtestcase.cpp:448
#21 0x00007ffff7f44184 in QTest::TestMethods::invokeTestOnData (this=0x7fffffffdba0, index=0) at /usr/src/debug/qt6-base/qtbase/src/testlib/qtestcase.cpp:1083
#22 0x00007ffff7f524fa in QTest::TestMethods::invokeTest (this=0x7fffffffdba0, index=<optimized out>, tag=..., watchDog=std::optional [no contained value]) at /usr/src/debug/qt6-base/qtbase/src/testlib/qtestcase.cpp:1385
#23 QTest::TestMethods::invokeTests (this=0x7fffffffdba0, testObject=<optimized out>) at /usr/src/debug/qt6-base/qtbase/src/testlib/qtestcase.cpp:1722
#24 QTest::qRun () at /usr/src/debug/qt6-base/qtbase/src/testlib/qtestcase.cpp:1946
#25 0x00007ffff7f477f5 in QTest::qExec (testObject=<optimized out>, argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/qt6-base/qtbase/src/testlib/qtestcase.cpp:1824
#26 0x000055555563b65d in main (argc=1, argv=0x7fffffffe088) at /home/user/Projects/PrismLauncher/tests/ResourceModel_test.cpp:91
```

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
caused by https://github.com/qt/qtbase/commit/bb542a55b28dd591709ed2c68e4505ec08fc62b5
