### ISSUE TITLE
My instances don't want to open on SteamOS

### ISSUE THREAD

**Issue by Suelvys** [PrismLauncher/PrismLauncher#2967]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher Linux Portable-9.0

### Version of Qt

Qt 5.12.8. and Qt 6 latest update 9.0

###  Notes

- I use Steamdeck with the latest SteamOS
- I use the Prism Launcher from the tar.gz files on the official website, because it allows me to access my custom javas
- Up until 8.4, everything worked perfectly

Well, I updated the Prism launcher from 8.4 to 9.0, after that, I noticed that my instances didn't want to open, even the ones I had just created, the button to open the folder also doesn't work, I decided to install Prisms in a new separate folder to test, and it continued the same way, both in Qt5 and Qt6, however, Qt6 seemed slower when opening the interfaces and loading content, I also got a similar log in some newly created instances without modloaders that I will put below.

Log:
```
Prism Launcher version: 9.0 (official)


Launched instance in online mode

login.microsoftonline.com resolves to:
    [2603:1056:2000:30::12, 2603:1056:2000:38::2, 2603:1056:2000:28::1, 2603:1056:2000:30::4, 2603:1056:2000:28::4, 2603:1056:2000:30::, 2603:1057:2:38::2, 2603:1057:2:28::1, 20.190.173.70, 40.126.45.17, 20.190.173.3, 20.190.173.129, 40.126.45.19, 20.190.173.130, 20.190.173.68, 40.126.45.18]


session.minecraft.net resolves to:
    [2620:1ec:bdf::34, 13.107.246.34]


textures.minecraft.net resolves to:
    [2620:1ec:bdf::34, 13.107.246.34]


api.mojang.com resolves to:
    [2620:1ec:bdf::34, 13.107.246.34]


Minecraft folder is:
/home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/instances/1.20.1/minecraft


Java path is:
/home/deck/Java/Executor/graalvm-jdk-17.0.12+8.1/bin/java


Java is version 17.0.12, using 64 (amd64) architecture, from Oracle Corporation.


AMD Custom APU 0405
Advanced Micro Devices, Inc. [AMD/ATI] VanGogh [AMD Custom GPU 0405] (rev ae)

Subsystem: Advanced Micro Devices, Inc. [AMD/ATI] VanGogh [AMD Custom GPU 0405]

Kernel driver in use: amdgpu

Main Class:
  net.minecraft.client.main.Main

Native path:
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/instances/1.20.1/natives

Traits:
traits FirstThreadOnMacOS
traits feature:is_quick_play_multiplayer
traits feature:is_quick_play_singleplayer
traits XR:Initial

Libraries:
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/org/lwjgl/lwjgl-glfw-natives-linux/3.3.2-lwjgl.1/lwjgl-glfw-natives-linux-3.3.2-lwjgl.1.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/org/lwjgl/lwjgl-jemalloc-natives-linux/3.3.1/lwjgl-jemalloc-natives-linux-3.3.1.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/org/lwjgl/lwjgl-natives-linux/3.3.1/lwjgl-natives-linux-3.3.1.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/org/lwjgl/lwjgl-openal-natives-linux/3.3.1/lwjgl-openal-natives-linux-3.3.1.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/org/lwjgl/lwjgl-opengl-natives-linux/3.3.1/lwjgl-opengl-natives-linux-3.3.1.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/org/lwjgl/lwjgl-stb-natives-linux/3.3.1/lwjgl-stb-natives-linux-3.3.1.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/org/lwjgl/lwjgl-tinyfd-natives-linux/3.3.1/lwjgl-tinyfd-natives-linux-3.3.1.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/com/github/oshi/oshi-core/6.2.2/oshi-core-6.2.2.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/com/google/code/gson/gson/2.10/gson-2.10.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/com/google/guava/guava/31.1-jre/guava-31.1-jre.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/com/ibm/icu/icu4j/71.1/icu4j-71.1.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/com/mojang/authlib/4.0.43/authlib-4.0.43.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/com/mojang/brigadier/1.1.8/brigadier-1.1.8.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/com/mojang/datafixerupper/6.0.8/datafixerupper-6.0.8.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/com/mojang/logging/1.1.1/logging-1.1.1.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/io/netty/netty-buffer/4.1.82.Final/netty-buffer-4.1.82.Final.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/io/netty/netty-codec/4.1.82.Final/netty-codec-4.1.82.Final.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/io/netty/netty-common/4.1.82.Final/netty-common-4.1.82.Final.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/io/netty/netty-handler/4.1.82.Final/netty-handler-4.1.82.Final.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/io/netty/netty-resolver/4.1.82.Final/netty-resolver-4.1.82.Final.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/io/netty/netty-transport-classes-epoll/4.1.82.Final/netty-transport-classes-epoll-4.1.82.Final.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/io/netty/netty-transport-native-epoll/4.1.82.Final/netty-transport-native-epoll-4.1.82.Final-linux-aarch_64.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/io/netty/netty-transport-native-epoll/4.1.82.Final/netty-transport-native-epoll-4.1.82.Final-linux-x86_64.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/io/netty/netty-transport-native-unix-common/4.1.82.Final/netty-transport-native-unix-common-4.1.82.Final.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/io/netty/netty-transport/4.1.82.Final/netty-transport-4.1.82.Final.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/it/unimi/dsi/fastutil/8.5.9/fastutil-8.5.9.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/net/java/dev/jna/jna-platform/5.12.1/jna-platform-5.12.1.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/net/java/dev/jna/jna/5.12.1/jna-5.12.1.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/org/apache/httpcomponents/httpcore/4.4.15/httpcore-4.4.15.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/org/slf4j/slf4j-api/2.0.1/slf4j-api-2.0.1.jar
  /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/libraries/com/mojang/minecraft/1.20.1/minecraft-1.20.1-client.jar

Native libraries:

Params:
  --username  --version 1.20.1 --gameDir /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/instances/1.20.1/minecraft --assetsDir /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/assets --assetIndex 5 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Launcher: standard

Java Arguments:
[-Xms512m, -Xmx4096m, -Duser.language=en]


Minecraft process ID: 179422


[18:40:40] [Datafixer Bootstrap/INFO]: 188 Datafixer optimizations took 217 milliseconds
[18:40:41] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[18:40:44] [Render thread/INFO]: Setting user: Suelvys
[18:40:44] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 build 7
libGL error: MESA-LOADER: failed to open radeonsi: /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/dri/radeonsi_dri.so) (search paths /usr/lib/dri, suffix _dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open radeonsi: /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/dri/radeonsi_dri.so) (search paths /usr/lib/dri, suffix _dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open swrast: /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/dri/swrast_dri.so) (search paths /usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
zenity: /home/deck/Aplicativos/PrismLauncher-Linux-Qt5-Portable-9.0/lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/libicuuc.so.72)
[18:40:44] [Render thread/WARN]: Failed to create window: 
ehn$a: GLFW error 65543: GLX: Failed to create context: GLXBadFBConfig
	at ehn.b(SourceFile:196) ~[minecraft-1.20.1-client.jar:?]
	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:build 7]
	at org.lwjgl.system.JNI.invokePPPP(Native Method) ~[lwjgl-3.3.1.jar:build 7]
	at org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:2024) ~[lwjgl-glfw-3.3.1.jar:build 7]
	at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:2197) ~[lwjgl-glfw-3.3.1.jar:build 7]
	at ehn.<init>(SourceFile:94) ~[minecraft-1.20.1-client.jar:?]
	at fkm.a(SourceFile:21) ~[minecraft-1.20.1-client.jar:?]
	at enn.<init>(SourceFile:486) ~[minecraft-1.20.1-client.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:211) ~[minecraft-1.20.1-client.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
O processo foi encerrado com o código 0.
Clipboard copy at: 22 Oct 2024 18:40:46 -0300
Clipboard copy at: 22 Oct 2024 19:06:20 -0300
```

### Steps to reproduce

Simply install Prism Launcher in a preferred folder, open it, install a Minecraft instance
Also try accessing the instance folder through the instance context menu

### Suspected cause

I suspect that it may be some library that is required in this update that is not natively available in SteamOS. I can't test it due to lack of memory, but maybe the PrismLauncher from flatpak might not have this problem because it includes libraries and other things, but it's just a guess.

If it is indeed something like that, it wouldn't be easy to solve it on SteamOS's side, due to its nature of blocking Arch packages and its system blocking writing, making it impossible to install the pending library.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Suelvys** [comment]
I apologize if I made a mistake there, I don't speak English natively and I use translators.

**Comment by TayouVR** [comment]
known issue, will be fixed in 9.1
in the meantime you could just use the flatpak and allow access to your javas via flatseal, or the KDE system settings:
![KDE_Plasma_5 27_Flatpak_Permissions-3736207027](https://github.com/user-attachments/assets/340e9166-0376-41e3-bc52-40a31d7d3099)

**Comment by Suelvys** [comment]
I ended up going back to 8.4, flatpacks consume a lot of memory, something that is missing in my 64gb Steamdeck, I'll wait for the 9.1 update patiently, but I appreciate the help

**Comment by Trial97** [comment]
This may be fixed in nightly builds by https://github.com/PrismLauncher/PrismLauncher/pull/2972#issuecomment-2439971220

Can you give it a try and report back if it works?
The nightly can be found https://nightly.link/PrismLauncher/PrismLauncher/workflows/trigger_builds/develop
(chose the file that contains both linux and portable in name)

**Comment by Trial97** [comment]
Hey can you try to reproduce it with the latest 9.2 ?

**Comment by Suelvys** [comment]
I did some tests here, a lot of things have improved, but the error of clicking to go to the folder in the instance still doesn't work in the tar.gz version. Furthermore, the Modrinth API has been working poorly since update 9.0, it takes a long time to make requests and to scan or download mod updates and other things, both in the tar.gz version and in the flatpak version.
#

**Comment by Octol1ttle** [comment]
the original issue (minecraft launching) appears to be fixed
