### ISSUE TITLE
Launcher lags/hangs when the log is rapidly changing

### ISSUE THREAD

**Issue by Justfines** [PrismLauncher/PrismLauncher#309]
### Version of Prism Launcher

Prism Launcher 5.0 on Windows

### Version of Qt

6.4

### Description of bug

When rapid log changes are happening (like when a singleplayer modpack or forge is loading), the entire launcher hangs (like on windows) instead of staying interactable

### Steps to reproduce

While having the console opening on game start, or already open
1. Use a pack that has a very rapid log writing (in my case I used project ozone 3 with optifine)
2. Load the pack or a sizable world in the pack
3. witness the launcher lockup

### Suspected cause

I think this is from the console trying to keep up with reading the log as it comes in.
 Might be more hassle than its worth (espessially since I'm unfamilar with Qt/c++) , but possibly decoupling the rest of the launcher from the instance console (like making it update async from the rest of the ui) might prevent this from happening later on, and would improve the experience when the log is going much to fast to keep up with

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Seegras** [comment]
Can confirm on Linux too. One way this happens is if you "kill <pid>" minecraft. it then does this (seen with strace): 

```
write(6, "\1\0\0\0\0\0\0\0", 8)         = 8
write(6, "\1\0\0\0\0\0\0\0", 8)         = 8
```

ad nauseam, and is completely unresponsive.

gdb says: 
```
0x00007ff1e34170af in __GI___poll (fds=0x55e801496510, nfds=15, timeout=25938)
    at ../sysdeps/unix/sysv/linux/poll.c:29
29	../sysdeps/unix/sysv/linux/poll.c: No such file or directory.
(gdb) bt
#0  0x00007ff1e34170af in __GI___poll
    (fds=0x55e801496510, nfds=15, timeout=25938)
    at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ff1e11929ae in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ff1e1192acc in g_main_context_iteration ()
    at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ff1e2148836 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007ff1e20ef17b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007ff1e20f72d6 in QCoreApplication::exec() ()
    at /lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x000055e7e2fa09e8 in main ()

```

**Comment by AnAwesomGuy** [comment]
this also happens to me
