### ISSUE TITLE
Unable to detect the forge install on all the mods 9

### ISSUE THREAD

**Issue by MegaShinySnivy** [PrismLauncher/PrismLauncher#3106]
### Operating System

Linux

### Version of Prism Launcher

9.0

### Version of Qt

6.8.0

### Description of bug

Attempted to install All The Mods 9 using Prism's built in installer. Was met with this lovely error, and going back a version did not fix it.

```
Exception caught from launcher
java.lang.RuntimeException: Unable to detect the forge installer!
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getDataFromInstaller(IFileDetector.java:157)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getInstallProfileExtraData(IFileDetector.java:136)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.checkExtraFiles(IFileDetector.java:170)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:38)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Exiting with ERROR
```

### Steps to reproduce

* Go to add instance
* Go to curseforge
* Type In All The Mods 9
* Add it as an instance, any 9x version will do
* Download all mods as asked
* Attempt to launch
* Cry

### Suspected cause

Unknown, but I did find these two older issues that may be related.

https://github.com/dscalzi/Nebula/issues/69

https://github.com/PrismLauncher/PrismLauncher/issues/1934

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by MegaShinySnivy** [comment]
Void this, my account was offline which caused it to fail
