### ISSUE TITLE
Pism Launcher 9.1 won't start Minecraft 1.21.3 / 1.21.4 instances with NeoForge

### ISSUE THREAD

**Issue by MC-Mods-Pete** [PrismLauncher/PrismLauncher#3208]
### Operating System

Ubuntu 24.04.1

### Version of Prism Launcher

Prism Launcher 9.1

### Version of Qt

Qt 6.2.4

### Description of bug

NeoForge instances for Minecraft 1.21.3 and 1.21.4 don't start at all and crash right away.

```
Checking: MC_SLIM
Checking: MERGED_MAPPINGS
Checking: MAPPINGS
Checking: MC_EXTRA
Checking: MOJMAPS
Checking: PATCHED
Checking: MC_SRG
Exception caught from launcher
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.IllegalStateException: Module named org.objectweb.asm was already on the JVMs module path loaded from /home/pete/Programs/common/libraries/org/ow2/asm/asm/9.7/asm-9.7.jar but class-path contains it at location /home/pete/Programs/PrismLauncher-Linux-Qt6-Portable-9.1/libraries/org/ow2/asm/asm/9.7/asm-9.7.jar
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:139)
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	... 5 more
Exiting with ERROR
Process exited with code 2.
Clipboard copy at: 14 Dec 2024 23:29:58 +0100
```

### Steps to reproduce

Create a new Minecraft instance with NeoForge 1.21.3 or 1.21.4 and try to start it.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by MC-Mods-Pete** [comment]
Seems to be an issue with my installation...
