### ISSUE TITLE
Add "use MGL GLFW" setting for macos 

### ISSUE THREAD

**Issue by x-0D** [PrismLauncher/PrismLauncher#3252]
### Role

I play Prism Launcher with mods on macos arm64 devices 

### Suggestion

I want setting toggle to use MGL (metal implementation of missing opengl 4), just like "use zink" on linux.

### Benefit

So i'm able to run mods that not ported correctly on macos (Valkyrien Skies 2 with Distant horizons and create are unable to launch on vanilla glfw)

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I successfully compiled 
https://github.com/openglonmetal/MGL
On macos sequoia 15.2 by following these instructions 
https://github.com/WizzerWorks/MGL/wiki/Apple-Silicon-MacOS-Build-Instructions
Then placed libMGL.dylib and libGLFW.dylib into `/Applications/Prism Launcher.app/Contents/MacOS/`, did

```
sudo codesign --force --deep --sign - /Applications/Prism\ Launcher.app/
```

And selected "use custom libGLFW.dylib" in launcher, with pointing `/Applications/Prism\ Launcher.app/Contents/MacOS/libGLFW.dylib`. After that i'm able to play Minecraft Fabric 1.20.1 with Distant Horizons, Create, Valkyrien Skies and other mods.

**Comment by x-0D** [comment]
[libMGL-main-sequoia-15.2 03.21.32.zip](https://github.com/user-attachments/files/18274069/libMGL-main-sequoia-15.2.03.21.32.zip)
Here are already compiled libs to test.

**Comment by x-0D** [comment]
Bump

**Comment by Aces-and-Jacks** [comment]
So you got mgl to work on prism launcher? Am I reading that right?

**Comment by Aces-and-Jacks** [comment]
Wow, still trying to figure out, but amazing

**Comment by Aces-and-Jacks** [comment]
~~Do you need the xcode application to do the build mgl part?~~ Nevermind, I  think I figured it out.

**Comment by x-0D** [comment]
> So you got mgl to work on prism launcher? Am I reading that right?

Yes, MGL works with the prism launcher

> Do you need the xcode application to do the build mgl part?

Yes. you need xcode installed and homebrew.

**Comment by Aces-and-Jacks** [comment]
-~~How do you know if it worked? I tried looking at the logs but there's nothing indicating a file path to the libGLFW. And I don't notice anything different. I'm thinking the F3 menu but I currently can't test at the moment. 
Edit: I loaded the game and it shows OpenGL 4.1.~~ I guess based on  

> unable to launch on vanilla glfw

I can test by using default glfw


-And also does doing the path to libGLFW also use the MGL file? 

-And lastly, at least from what I've read, you put them both in the MacOS folder of prismlauncher.app/contents/macos?

Thank you for any help given

**Comment by Aces-and-Jacks** [comment]
Sorry for the multiple messages. I think I came to a wrong conclusion about this. I assumed it'd add similar to what https://github.com/r58Playz/mglmod tried to do. But one is better for some mods while the other is more of a full opengl 4.6 port. 

Basically I overestimated using mgl

**Comment by x-0D** [comment]
> - And also does doing the path to libGLFW also use the MGL file?

This is modified `libGLFW.dylib` that requires `libMGL.dylib` to work. It's compiled with MGL project and copied to PrismLauncher Application. Copying is needed to sign with one the same signature custom libGLFW, libMGL and PrismLauncher. Without signing it won't start.

> How do you know if it worked?

After custom libGLFW.dylib loaded, i'm able to play Minecraft Fabric 1.20.1 with Distant Horizons, Create and Valkyrien Skies at the same time. (these mods won't work with each other because somewhere opengl4.6 required to integrate with each other). Without MGL-patched GLFW, they simply crashes minecraft on world opening.

Tested on macbook pro M2

> Sorry for the multiple messages.

It's OK to ask anything you need to know about. I checking my mail once per day.

**Comment by Aces-and-Jacks** [comment]
> they simply crashes minecraft on world opening.

While I do think the mgl version may have helped, the `LWJGL 3` provided already works. At least for me. I was able to open up a world with those mods with no issue. The first time it crashed but after that it was ok. I tested with a few different instance creations. Both with it on and off.

**Comment by x-0D** [comment]
In any case, I think adding the optional option to use the MGL backend, similar to the Zink backend on linux, would be nice.

**Comment by Aces-and-Jacks** [comment]
Yeah, I agree with that

**Comment by MrWindDog** [comment]
I agree as well. Although it doesn't fix everything (voxy still crashes, along with a few other I tested), it is a definite improvement.

**Comment by Arbifoxx** [comment]
Disregard that, is anyone else getting this issue when launching? I got it compiled, I had the wrong branch

[m[32m[02:30:56.024] [main/INFO] [Launcher/MODLAUNCHER]: JVM identified as Azul Systems, Inc. OpenJDK 64-Bit Server VM 21.0.4+7-LTS 
[m[32m[02:30:56.025] [main/INFO] [Launcher/MODLAUNCHER]: ModLauncher 11.0.5+main.901c6ea8 starting: java version 21.0.4 by Azul Systems, Inc.; OS Mac OS X arch aarch64 version 26.0 
[m[32m[02:30:56.132] [main/INFO] [loading.ImmediateWindowHandler/]: Loading ImmediateWindowProvider fmlearlywindow 
[m[32m[02:30:56.303] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.6 
[mAssertion failed: (_glfw.mgl.handle), function _glfwInitMGL, file mgl_context.m, line 101.
Process crashed with exitcode 6.

**Comment by Arbifoxx** [comment]
Even after doing all of this and using the custom libGLFW, is anyone getting this?

GLFW error 65543: MGL: OpenGL 4.6 and above supported on MGL.

Please make sure you have up-to-date drivers (see aka.ms/mcdriver for instructions).

I've tried my own compiled dylibs and the ones listed above.

EDIT: After adding a bit of debugging info, it seems OpenGL 3.2 is still being used.

**Comment by gitcakes** [comment]
Bump

**Comment by x-0D** [comment]
Looks like there's no more GLFW target to build on https://github.com/openglonmetal/MGL project. looks likely project got a little messy and no one cares about it. If someone interested to use libGLFW.dylib with libMGL.dylib and have any success on macos 26.1, please leave instructions how you made it.

As far i know, this repo is good starting point:

https://github.com/julcst/MGL/tree/b3241a5746bf42765502de068c07f836e493229a

by now, there's one undocumented thing you need to do to compile:

```
brew install glm

# other commands as expected:
mkdir build && cd build
cmake ..
make -j4

# but seems there's no GLFW in targets or libGLFW.dylib, only fresh version of libMGL.dylib
```

**Comment by x-0D** [comment]
> Even after doing all of this and using the custom libGLFW, is anyone getting this?
> 
> GLFW error 65543: MGL: OpenGL 4.6 and above supported on MGL.
> 
> Please make sure you have up-to-date drivers (see aka.ms/mcdriver for instructions).
> 
> I've tried my own compiled dylibs and the ones listed above.
> 
> EDIT: After adding a bit of debugging info, it seems OpenGL 3.2 is still being used.

Just got the same results. I don't know exactly why this happens, cause i'm able to launch the game year ago.... Trying to investigate the problem to find out how it could be solved.

**Comment by Arbifoxx** [comment]
I had that problem too when I tried to do this a while ago. Never solved it ugh.

**Comment by x-0D** [comment]
@Arbifoxx try this:

[libMGL-main-sequoia-15.2 03.21.32-patched.zip](https://github.com/user-attachments/files/24241855/libMGL-main-sequoia-15.2.03.21.32-patched.zip)

Here is how i patched libraries:

```
# here is what i did (took that from mglmod)
# if this does not help, determine valid path to change
otool -l libGLFW.dylib | grep -i libmgl.dylib
# then replace `/usr/local/lib/libMGL.dylib` with your path discovered
install_name_tool -change /usr/local/lib/libMGL.dylib @rpath/libMGL.dylib libGLFW.dylib
install_name_tool -add_rpath @loader_path libGLFW.dylib
codesign --force --deep --sign - libGLFW.dylib
```

this is old build from 30.12.2024, but patched to search `libMGL.dylib` in the same folder where libGLFW.dylib located.
Also, there's modrinth mrpack from 2024 that works with this opengl 4.6

Since something happened in libMGL, newer 2025 build just crashes game with 
GLFW error 65543: MGL: OpenGL 4.6 and above supported on MGL.
Can you try this and give feedback how it launches?

UPD: tested that microsoft java does not work with MGL. Use arm64 zulu JDK instead on macos M-series.

UPD2: confirmed it work with newest versions of Minecraft (1.21.11) but still needs to change java to arm64 ZuluJDK 21.

**Comment by ggenesiss** [comment]
@x-0D 

Even after patching the libraries with the commands stated above and installing the arm64 build Azul JDK, it still returns “GLFW error 65543: MGL: OpenGL 4.6 and above supported on MGL”

I’m on version 1.21 and on an M1 iMac running Tahoe 26.2

Does the patch.zip file you provided work for Tahoe or is just for Sequoia?

**Comment by x-0D** [comment]
@ggenesiss [libMGL-main-sequoia-15.2 03.21.32-patched.zip](https://github.com/user-attachments/files/24241855/libMGL-main-sequoia-15.2.03.21.32-patched.zip) works on tahoe, they just compiled on sequoia 30 dec 2024, it can be outdated, but it works. also, they already patched to work as expected.

new builds cause GLFW error 65543: MGL: OpenGL 4.6 and above supported on MGL

old builds works. 

there's mrpack with modspack to try out. it confirmed to work with libMGL and libGLFW (30 dec 2024)

**Comment by x-0D** [comment]
@ggenesiss Have you tried this? I'd appreciate your feedback, thanks.

**Comment by ggenesiss** [comment]
@x-0D I have and it still returned GLFW error 65543

I'd imagine the issue is that you'd need to compile it on your own machine and not download someone else's build. Then again someone else did mention they tried their own builds plus the ones you've provided and still couldn't get it to work properly.

If it isn't too much of a problem, would you mind providing a step by step guide as to how you built your dylib's? Whenever I tried building my own it would fail...

 Many thanks!

**Comment by x-0D** [comment]
@ggenesiss 

Here is exact steps that i've done:

#### 00. prepare step
```
brew install glm
```

#### 01. First of all, try to compile original library
```
git clone https://github.com/openglonmetal/MGL.git MGL
cd MGL
cd external
./clone_external.sh
./build_external.sh
```

if build_external it fails, search for default argument declaration in file and remove `=Null` in header definition

```diff
 This is just example, read build logs to determine file that cause error.
- void MGLswapBuffers(GLMContext ctx=NULL);
+ void MGLswapBuffers(GLMContext ctx);
```

maybe here, i don't remember [gh::openglonmetal/MGL:/MGL/include/MGLContext.h#L42](https://github.com/openglonmetal/MGL/blob/792cbabe22eaf2bb68450956aca0e6d364520cfa/MGL/include/MGLContext.h#L42)
when these are done, open MGL.xcodeproj in xcode and try to build MGL target. feel frustration about build fails, switch to next try.


#### 02. Second try, using project fork with CMake
```
git clone https://github.com/x-0D/MGL.git MGL_cmake
cd MGL_cmake
mkdir build
cd build
cmake ..
make -j 4

# then search in compiled code:
find . -type f | grep libmgl.dylib
find . -type f | grep libglfw | grep dylib

```
Copy libmgl.dylib and libglfw.dylib to the same folder.

Then patch libglfw you've found:

```
# credits to mglmod developer.
# 1. verify that libmgl.dylib path is equals to `/usr/local/lib/libMGL.dylib`
otool -l libglfw.dylib | grep -i libmgl.dylib
# 2. if it is not, replace `/usr/local/lib/libMGL.dylib` in the script below with your path discovered
install_name_tool -change /usr/local/lib/libMGL.dylib @rpath/libMGL.dylib libglfw.dylib
install_name_tool -add_rpath @loader_path libglfw.dylib
codesign --force --deep --sign - libglfw.dylib
```

Now you're ready to try `libglfw.dylib`

it should run, but shows up an error:
`GLFW error 65543: MGL: OpenGL 4.6 and above supported on MGL`

throw these dylibs away and use [libMGL-main-sequoia-15.2.03.21.32-patched.zip](https://github.com/user-attachments/files/24241855/libMGL-main-sequoia-15.2.03.21.32-patched.zip)

every time macos shows up error about content from internet, "Move to Trash" or "Cancel", do cancel and go to macos settings, privacy, scroll to the bottom, and allow execution unverified dylib.

now it should run.

If you ok to try it on-line, you can reach me in discord or telegram by `@appleroot` tag, i would happy to help. (TODO for ME in future: edit this message, remove contact info)

**Comment by lucamignatti** [comment]
when it runs, does it say its using mgl and opengl 4.6 in f3? i am attempting to get mgl up and running on 26.1 with minecraft 1.21.11, and those binaries also have error 65543 for me. digging into the code minecraft appears to use unimplemented opengl features? Also, you can get through error 65543 by using the mod threatenGL and patching it to force opengl 4.6 on macOS (by default it forces 4.1), though this hits path after path of broken features. I am currently working off your fork on implementing needed features as it errors, though theres no telling if ill ever get it to work.

**Comment by x-0D** [comment]
when it runs MGL, it works with mrpack modpack provided in [libMGL-main-sequoia-15.2.03.21.32-patched.zip](https://github.com/user-attachments/files/24241855/libMGL-main-sequoia-15.2.03.21.32-patched.zip)

If you try to run modpack without libMGL, it just crashes.

NOTE: Newer versions of libMGL are broken, they causing `GLFW error 65543: MGL: OpenGL 4.6 and above supported on MGL` while compiled ones from libMGL-main-sequoia-15.2.03.21.32-patched.zip don't do that.

Possibly, maybe it can be compiled again into working state using this commit in original repository:

https://github.com/openglonmetal/MGL/tree/44da8c754bcba2731fc00ca5b6c972af2d28df1d

as i said earlier, libMGL-main-sequoia-15.2.03.21.32 compiled 30 dec 2024, so maybe using commit from that time should help.

```
git clone https://github.com/openglonmetal/MGL.git MGL
cd MGL
git checkout 44da8c754bcba2731fc00ca5b6c972af2d28df1d
cd external
./clone_external.sh
./build_external.sh

# then open MGL in Xcode and compile MGL and GLFW targets. after compilation, find artifacts ( i don't remember where xcode place compiled dylibs, sorry)
```

**Comment by lucamignatti** [comment]
I cannot get those compiled binaries to work. Using that modpack it does appear to run for longer, but it still crashes. it does, however, run without MGL. The existence of: https://github.com/r58Playz/mglmod seems to imply that MGL cannot run minecraft. Also in the code, there are missing features minecraft relies on when running with openGL 4.6 which is required by MGL (even at that commit). Are you sure your running it with opengl 4.6 and MGL?

**Comment by Arbifoxx** [comment]
Just wanted to add something I discovered while trying to compile MGL, if the xcode project is complaining about not having libSPVRemapper.a, you have to checkout commit 8a85691a0740d390761a1008b4696f57facd02c4 for glslang and recompile. It will then generate libSPVRemapper.

**Comment by Arbifoxx** [comment]
Trying to run the modpack, is anyone else getting this?

[12:56:20] [main/INFO]: Loading EarlyLoadingScreen on ClassLoader net.fabricmc.loader.impl.launch.knot.KnotClassLoader
[12:56:20] [main/INFO]: Patching KnotClassDelegate for class loader issues
[12:56:20] [main/INFO]: Patching KnotClassDelegate.loadClass
[12:56:20] [main/INFO]: Patching FabricLoaderImpl for entrypoint information
[12:56:20] [main/INFO]: Patching FabricLoaderImpl.invokeEntrypoints
[12:56:20] [main/INFO]: Patching me/jellysquid/mods/sodium/client/compatibility/workarounds/Workarounds to allow early usage
[12:56:20] [main/INFO]: Patching me/jellysquid/mods/sodium/client/compatibility/workarounds/Workarounds to allow early usage
[12:56:20] [main/INFO]: Patching me/jellysquid/mods/sodium/client/compatibility/workarounds/nvidia/NvidiaWorkarounds to allow early usage
[12:56:20] [main/INFO]: Patching me/jellysquid/mods/sodium/client/compatibility/workarounds/nvidia/NvidiaWorkarounds to allow early usage
[12:56:20] [main/INFO]: Patching me/jellysquid/mods/sodium/client/compatibility/workarounds/nvidia/NvidiaWorkarounds$1 to allow early usage
[12:56:20] [main/INFO]: Patching me/jellysquid/mods/sodium/client/compatibility/workarounds/nvidia/NvidiaWorkarounds$1 to allow early usage
[12:56:20] [main/INFO]: Patching me/jellysquid/mods/sodium/client/compatibility/environment/probe/GraphicsAdapterProbe to allow early usage
[12:56:20] [main/INFO]: Patching me/jellysquid/mods/sodium/client/compatibility/environment/probe/GraphicsAdapterProbe to allow early usage
[12:56:20] [main/INFO]: Initializing LoadingScreenManager...
[12:56:20] [main/INFO]: Creating early window...
[12:56:21] [main/INFO]: Searching for graphics cards...
Assertion failed: (_glfw.mgl.handle), function _glfwInitMGL, file mgl_context.m, line 101.
Process crashed with exitcode 6.

EDIT: Was user error, oops! But now I also get
GLFW error 65543: MGL: OpenGL 4.6 and above supported on MGL.

Please make sure you have up-to-date drivers (see aka.ms/mcdriver for instructions).

I'm using the 44da8c754bcba2731fc00ca5b6c972af2d28df1d commit of MGL

I've also noticed that, even with the modpack, the patched dylibs don't work as well.

**Comment by lucamignatti** [comment]
[threatengl-fabric-2.0.4-release.10.jar.zip](https://github.com/user-attachments/files/24332452/threatengl-fabric-2.0.4-release.10.jar.zip)

there is a patched threatenGL jar for 1.21.11 that forces opengl 4.6 on mac. it will allow you to try and use MGL. it will error because MGL doesnt support everything it needs, but maybe you can get futher than I. I am currently attempting to update mglmod to 1.21.11 as that appears to be the path of least resistance. I also have a build of MGL that runs minecraft without crashing, however it currently just displays a black screen as i skipped implimenting many features and just removed the assertations to avoid the crashes. there is much work to do to run minecraft straight up.

**Comment by Arbifoxx** [comment]
[13:21:22] [Render thread/INFO]: ThreatenGL will threaten Minecraft soon...
[13:21:22] [Render thread/INFO]: Using GLFW Version 3.4.0 Cocoa NSGL Null EGL OSMesa monotonic, not to be confused with OpenGL version.
[13:21:22] [Render thread/INFO]: Backend library: LWJGL version 3.3.3-snapshot
[13:21:22] [Render thread/WARN]: Detected unexpected shutdown during last game startup: resetting fullscreen mode
[13:21:22] [Render thread/INFO]: Threatened Minecraft to use GLFW_CONTEXT_VERSION_MAJOR 4
[13:21:22] [Render thread/INFO]: Threatened Minecraft to use GLFW_CONTEXT_VERSION_MINOR 6
[13:21:22] [Render thread/INFO]: Forced GLFW_OPENGL_PROFILE to GLFW_OPENGL_CORE_PROFILE on macOS
[13:21:22] [Render thread/INFO]: Forced GLFW_OPENGL_FORWARD_COMPAT to GLFW_TRUE on macOS
[13:21:22] [Render thread/WARN]: Failed to get system info for Render Extensions
java.lang.IllegalStateException: Can't getDevice() before it was initialized
	at knot//com.mojang.blaze3d.systems.RenderSystem.getDevice(RenderSystem.java:299)
	at knot//net.minecraft.class_310.method_68671(class_310.java:2527)
	at knot//net.minecraft.class_6396.method_37123(class_6396.java:78)
	at knot//net.minecraft.class_310.method_37274(class_310.java:2527)
	at knot//net.minecraft.class_310.method_22681(class_310.java:2497)
	at knot//net.minecraft.client.main.Main.main(Main.java:243)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:514)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:72)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 2025-12-24 13:21:22
Description: Initializing game

java.lang.IllegalStateException: There is no OpenGL context current in the current thread.
	at knot//org.lwjgl.opengl.GL.createCapabilities(GL.java:382)
	at knot//org.lwjgl.opengl.GL.createCapabilities(GL.java:311)
	at knot//org.lwjgl.opengl.GL.createCapabilities(GL.java:295)
	at knot//net.minecraft.class_10865.<init>(class_10865.java:77)
	at knot//com.mojang.blaze3d.systems.RenderSystem.initRenderer(RenderSystem.java:205)
	at knot//net.minecraft.class_310.<init>(class_310.java:533)
	at knot//net.minecraft.client.main.Main.main(Main.java:234)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:514)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:72)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

Sadly, I did not get any further than you. It crashed as you said it would, which I'm not too surprised about.

**Comment by x-0D** [comment]
@lucamignatti , how problem looks like when you trying to use those dylibs?

UPD:
I'm confused. Looks like something happened and now those modpack works either custom GLFW selected or not. that's not what i expecting. Does compiling MGL change something... It should crash at world open, if no custom libGLFW provided.

**Comment by lucamignatti** [comment]
[Here](https://mclo.gs/TvqQKfL) is the log when i run that pack with those dylibs.

**Comment by ggenesiss** [comment]
I built my own dylib’s via cmake and it gave me libGLFW.3.4.dylib instead of libGLFW.dylib

Nevertheless I patched it and did all the usual stuff
Opening the game still returned “GLFW error 65543”

Then I redownloaded the patch that @x-0D provided and it still returned the error…

**Comment by x-0D** [comment]
Now, i'm very confused. Doing clean install of PrismLauncher and libGLFW, even patched from 2024, causing `GLFW error 65543: MGL: OpenGL 4.6 and above supported on MGL`. Something not good with it... Feeling gaslighted. Will try investigate what exactly changed when i have time.

**Comment by lucamignatti** [comment]
MGL cannot run minecraft in its current state. that specific error is caused by minecraft being hardcoded to attempt to use openGL 4.1 on mac. the patched threatenGL above forces minecraft to try to use opengl 4.6, which allows you to see the real errors with MGL, and there are many. MGLmod exists which directly patches minecrafts shaders to only use features that support mgl, and it does work. problem is its not up to date and wont support any mods that modify shaders. this means sodium, iris, voxy, DH, etc simply wont work. The best approach would be to update MGL to support the requires features. this is a lot of work but also doesnt require full compliance with openGL 4.6 and so may be doable.

**Comment by ggenesiss** [comment]
Well I guess that settles that...

Cheers to whoever tries taking on this issue themselves! (I have next to nothing in coding experience 🤣)

**Comment by AArch64Gamer** [comment]
I'm new to this thread, and I was trying to achieve the same outcome of MC using OpenGL 4.6 on macOS. I was trying to compile Zink on macOS, but I couldn't get it to compile. I'll try soon with MGL and see if I get any results.

**Comment by DioEgizio** [comment]
> MGL cannot run minecraft in its current state. that specific error is caused by minecraft being hardcoded to attempt to use openGL 4.1 on mac. the patched threatenGL above forces minecraft to try to use opengl 4.6, which allows you to see the real errors with MGL, and there are many. MGLmod exists which directly patches minecrafts shaders to only use features that support mgl, and it does work. problem is its not up to date and wont support any mods that modify shaders. this means sodium, iris, voxy, DH, etc simply wont work. The best approach would be to update MGL to support the requires features. this is a lot of work but also doesnt require full compliance with openGL 4.6 and so may be doable.

yeah i was confused at first by this issue too because afaik mgl doesn't support everything. I guess zink + kosmickrisp might be the best bet for macOS in the near future?

**Comment by lucamignatti** [comment]
<img width="966" height="620" alt="Image" src="https://github.com/user-attachments/assets/644c1827-dcce-4236-af16-0fc1fee1e1ee" /> I have managed to get zink+kosmickrisp working, and it seems like the best path forward for openGL 4.6 on mac. This combo is not currently functional though so i had to hack around a lot of issues. As you can see from the hotbar in the screenshot, it is buggy. Shaders and voxy work, though performance is not great.

**Comment by Arbifoxx** [comment]
Woah, still awesome progress though!

**Comment by AArch64Gamer** [comment]
Wow that's cool! I still haven't managed to get anything built on my end (I lack software skills unrelated to Blender). If you don't mind, could you upload the libraries that you built?

**Comment by lucamignatti** [comment]
You will have to compile kosmickrisp yourself at a minimum to get correct a correct vulkan icd, so i cant just upload the libraries. i put together a little writeup on getting it working though because i do think some of the stuff i did could be useful to others later on [here](https://gist.github.com/lucamignatti/5312f5e937de2ba44256ecba6de54cc2). it includes build instructions. its not really playable as is though. Not all shaders work as kosmickrisp doesnt have everything they need, and voxy does not work (slight correction from before, i thought it was but it turned out i just had a high render distance set). that being said in the case of voxy its just indirect openGL missing which itself is only missing a few extensions in kosmickrisp. it seems like those extensions shouldn't be incredibly difficult to implement, though no ones done it yet.

**Comment by AArch64Gamer** [comment]
Ah ok. Thanks for the instructions!
