### ISSUE TITLE
java8 on minecraft 1.8.9 not launching

### ISSUE THREAD

**Issue by Ahptt** [PrismLauncher/PrismLauncher#567]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 5.2

### Version of Qt

Qt version 6.4.1.

### Description of bug

Upon attempting to boot Minecraft 1.8.9 with Java 8 (/usr/lib/jvm/java-8-openjdk-amd64/bin/java), the launch instantly fails with the following output. This occurs even with a vanilla entry, but also with a modded scenario through forge.

```

Dec 07, 2022 9:03:21 PM org.prismlauncher.EntryPoint listen
SEVERE: Exception caught from launcher.
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:74)
Caused by: java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
	at java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:807)
	at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:886)
	at org.lwjgl.LinuxSysImplementation.<clinit>(LinuxSysImplementation.java:50)
	at org.lwjgl.Sys.createImplementation(Sys.java:131)
	at org.lwjgl.Sys.<clinit>(Sys.java:116)
	at ave.J(SourceFile:2539)
	at net.minecraft.client.main.Main.main(SourceFile:41)
	... 9 more
Dec 07, 2022 9:03:21 PM org.prismlauncher.EntryPoint main
INFO: Exiting with 1
Process exited with code 1.
```

### Steps to reproduce

1. Prism Launcher 5.2 on Qt 6.4.1
2. vanilla 1.8.9 with LWJGL 2  version  2.9.4-nightly-20150209
3. Launch and the error occurs

### Suspected cause

Not sure of reason. Here are my installed java packages. I have installed PrismLauncher via [nix-env](https://search.nixos.org/packages?channel=22.11&show=prismlauncher&from=0&size=50&sort=relevance&type=packages&query=prismlauncher)

```
❯ nala list --installed | grep java
ca-certificates-java 20220719 [Debian/sid main]
java-common 0.73 [Debian/sid main]
javascript-common 11+nmu1 [Debian/sid main]

~
❯ nala list --installed | grep openjdk
openjdk-17-jre-headless 17.0.5+8-2 [Debian/sid main]
openjdk-8-jre-headless 8u352-ga-1 [Debian/sid main]
```

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
You should install the non-headless version of Java

**Comment by pandaninjas** [comment]
> You should install the non-headless version of Java

Maybe there could be a warning if the JDK is headless?
