### ISSUE TITLE
Game crashes when launching a modpack (VaultHunters) after executing for 3-4secs. Seems to come from modlauncher.

### ISSUE THREAD

**Issue by mactemporal** [PrismLauncher/PrismLauncher#643]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 6.0

### Version of Qt

Qt 6.4.1

### Description of bug

When downloading from Curseforge the modpack Vault Hunters 2nd Edition and launching the game it loads for about 3sec then crashes with the error code : 
```
[13:20:12] [main/INFO] [STDERR/]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 1:0 token recognition error at: '~'
Exception caught from launcher
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Caused by: java.lang.NoSuchMethodError: sun.security.util.ManifestEntryVerifier.<init>(Ljava/util/jar/Manifest;)V
	at cpw.mods.modlauncher.SecureJarHandler.createCodeSource(SecureJarHandler.java:66)
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:275)
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.spongepowered.asm.service.modlauncher.ModLauncherClassProvider.findClass(ModLauncherClassProvider.java:67)
	at org.spongepowered.asm.launch.platform.MixinConnectorManager.loadConnectors(MixinConnectorManager.java:70)
	at org.spongepowered.asm.launch.platform.MixinConnectorManager.inject(MixinConnectorManager.java:59)
	at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:196)
	at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:202)
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:201)
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:195)
	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$9(LaunchPluginHandler.java:97)
	at java.util.HashMap.forEach(HashMap.java:1290)
	at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:97)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:52)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
	... 8 more
Exiting with ERROR
```

### Steps to reproduce

1. Install VaultHunters
2. launch the instance

### Suspected cause

Seems to come from modlauncher 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
https://prismlauncher.org/wiki/overview/frequent-issues/#minecraft-1.16.5-with-minecraft-forge-and-java-8u321+

**Comment by mactemporal** [comment]
I feel like a dumbass sorry
And thank you very much!

**Comment by RossComputerGuy** [comment]
Solution for Flatpaks users? There's only Java 17.0.4.1 and 1.8.0_352.

**Comment by DioEgizio** [comment]
As https://prismlauncher.org/wiki/overview/frequent-issues/#minecraft-1.16.5-with-minecraft-forge-and-java-8u321+ says, updating your forge
