### ISSUE TITLE
Since 6.1, Forge cannot be loaded with a Quiltflower jar added to mc

### ISSUE THREAD

**Issue by Frontear** [PrismLauncher/PrismLauncher#697]
### Operating System

Windows 11

### Version of Prism Launcher

Prism Launcher 6.1

### Version of Qt

Qt 6.4.0

### Description of bug

Adding a quiltflower jar to MC, then running a forge instance should work and allow mc to load fine. Instead, it crashes claiming to have found another module named minecraft. This issue was NOT present in 6.0, I was able to run minecraft fine and I think I have mc logs (maybe not launcher logs) from the time.

https://mclo.gs/qKzOIb3: log of crash
https://mclo.gs/grjPFv0: log of when it worked (not that useful but proving it did actually work)

snippet from crash:
```
Caused by: java.lang.module.ResolutionException: Module minecraft reads another module named minecraft
--
208 | at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
209 | at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:719)
210 | at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
211 | at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
212 | at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
213 | at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
214 | at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
215 | at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
216 | at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
217 | at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
218 | at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
219 | at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
220 | ... 8 more
```

### Steps to reproduce

* Create a new forge instance
* Add quiltflower-1.9.0.jar to minecraft jars
* Run

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Frontear** [comment]
closing because 5.0 cant run either. additionally logs do not contain quiltflower as dependency from when it worked. likely a forge side issue since fabric works fine
