### ISSUE TITLE
(M1/M2 Apple Silicon) Colours are inverted on older Minecraft versions

### ISSUE THREAD

**Issue by sanjerno** [PrismLauncher/PrismLauncher#698]
### Operating System

macOS

### Version of Prism Launcher

Prism Launcher 6.1

### Version of Qt

QT 6.3.0

### Description of bug

When playing older minecraft versions on Apple M2 (and from what I've found M1's as well) colours seem to be inverted with no way of setting them to a normal colour scheme. This affects all versions that I've tested up to 1.5.2. 1.6.1 and after no longer are affected.

I have tried solutions listed here:
- [https://www.reddit.com/r/macgaming/comments/mcywor/a_rough_patch_for_the_minecraft_bgr_color_schemes](https://www.reddit.com/r/macgaming/comments/mcywor/a_rough_patch_for_the_minecraft_bgr_color_schemes)
- [https://www.reddit.com/r/Minecraft/comments/lawhpi/weird_colour_inversion_on_beta_version_of](https://www.reddit.com/r/Minecraft/comments/lawhpi/weird_colour_inversion_on_beta_version_of)

Neither of which have any meaningful solutions.

Images:
<img width="966" alt="image" src="https://user-images.githubusercontent.com/91035826/210192884-644fe681-6c96-403c-aed0-cb6dcce4483d.png">
<img width="966" alt="image" src="https://user-images.githubusercontent.com/91035826/210193070-b3d79835-0f32-4517-a390-5922e1218553.png">

### Steps to reproduce

- On an Apple Silicon Mac make a new instance of any version belew 1.6.1
- Launch the game and watch the colour show!

### Suspected cause

My guess would be something to do with java x64. I honestly have no clue though.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ghost** [comment]
See https://github.com/MinecraftMachina/ManyMC/issues/39#issuecomment-1229540429

And https://github.com/betacraftuk/legacyfix which says it fixes "flipped color channels on versions before 13w16a on Silicon Macs" and many more issues with legacy versions of minecraft

**Comment by Scrumplex** [comment]
It's probably this code right here. I wonder if you could fix it with a mod instead.

**Comment by wilebaldo** [comment]
I have the same issue.

How i will use the legacyfix?

**Comment by ghost** [comment]
> How i will use the legacyfix?

1. Download [this file](https://gist.githubusercontent.com/678435021/0f1a54bb6a08f3515dd7bafc429c9a29/raw/6fa627e318ef8a8f4ed428aa9b80cc05242febae/LegacyFix.json)
2. Click on `Import Components` in the versions tab of the instance and select the downloaded file. It should look something like this:
![image](https://user-images.githubusercontent.com/110736028/223719153-863e72e2-7f6d-4680-83ea-fc10e508ddea.png)
3. Launch the instance

**Comment by wilebaldo** [comment]
> > How i will use the legacyfix?
> 
> 1. Download [this file](https://gist.githubusercontent.com/678435021/0f1a54bb6a08f3515dd7bafc429c9a29/raw/6fa627e318ef8a8f4ed428aa9b80cc05242febae/LegacyFix.json)
> 2. Click on `Import Components` in the versions tab of the instance and select the downloaded file. It should look something like this:
>    ![image](https://user-images.githubusercontent.com/110736028/223719153-863e72e2-7f6d-4680-83ea-fc10e508ddea.png)
> 3. Launch the instance

------Thank you, now is working.

Sorry I edit, is not working, trying to go any menu or open inventory the game crash, but now I can see the real colors. I will continue looking for to solve this.

**Comment by Kzhx111** [comment]
Any news on solving the issue? I have the same case as @wilebaldo :/

**Comment by wilebaldo** [comment]
> Any news on solving the issue? I have the same case as @wilebaldo :/
No, the solution they give me is fix the colors, but as soon I press the E, I or ESC to access the menu the game crash.

Look this video I made
https://www.youtube.com/watch?v=JJsPgKWpqR4

**Comment by Kzhx111** [comment]
Eventually, when I use Prism Launcher and go fullscreen mode (ctrl + fn + f11) the colors are **correct**. For windowed mode I couldn't make anything work 🤷

edit: without any legacy fix enabled*

**Comment by LeoMehraban** [comment]
I have the colors working, but, even following @wilebaldo's video, pressing escape, e, or pretty much any other button that isn't right or left click, the game crashes with a nullpointerexeption

**Comment by ghost** [comment]
Does this happen while the game is being translated with Rosetta 2? I haven't tested it.

**Comment by craftycodie** [comment]
> Does this happen while the game is being translated with Rosetta 2? I haven't tested it.

yes

**Comment by ghost** [comment]
> > Does this happen while the game is being translated with Rosetta 2? I haven't tested it.
> 
> 
> 
> yes

Interesting. I'd think Rosetta 2 would translate the binary properly. There are fixes being thrown around in this issue, but I haven't personally gotten any to work, and the documentation is severely lacking.

**Comment by craftycodie** [comment]
Legacyfix / betacraft’s solution to my understanding is to hook various functions involving images or color and swap channels. This is a bit messy, and misses a few spots, but it is fairly quick.

MineOnline’s solution is to grab the pixel buffer and draw a quad with it, this is slightly less messy and doesn’t miss anything, but it unsurprisingly has a significant impact on performance.

Im unaware of any other solutions in use.
The real solution is probably just to fix it in lwjgl itself.

**Comment by craftycodie** [comment]
> Legacyfix / betacraft’s solution to my understanding is to hook various functions involving images or color and swap channels. This is a bit messy, and misses a few spots, but it is fairly quick.
> 
> MineOnline’s solution is to grab the pixel buffer and draw a quad with it, this is slightly less messy and doesn’t miss anything, but it unsurprisingly has a significant impact on performance.
> 
> Im unaware of any other solutions in use. The real solution is probably just to fix it in lwjgl itself.

Having just dived through the code i think im mistaken on legacyfix, though im not entirely sure what it’s actually doing yet.

**Comment by otroof** [comment]
> > How i will use the legacyfix?
> 
>     1. Download [this file](https://gist.githubusercontent.com/678435021/0f1a54bb6a08f3515dd7bafc429c9a29/raw/6fa627e318ef8a8f4ed428aa9b80cc05242febae/LegacyFix.json)
> 
>     2. Click on `Import Components` in the versions tab of the instance and select the downloaded file. It should look something like this:
>        ![image](https://user-images.githubusercontent.com/110736028/223719153-863e72e2-7f6d-4680-83ea-fc10e508ddea.png)
> 
>     3. Launch the instance

Hi is there any change you still have the proper link to this file? The current link return error 404.
Thanks in advance, im also trying to get the colour fix on my mac

**Comment by Scrumplex** [comment]
I uploaded this file in one of our own repositories, so it'll stay up forever.

Just click on the download button on the top right on this page: https://github.com/PrismLauncher/files/blob/29245eb53dc22512c944efe0916a412c7a3518a1/components/betacraft-legacyfix.json

**Comment by LeoMehraban** [comment]
As you posted this, I found a slightly modified version of the file on my computer

{
    "+agents": [
		{
			"name": "uk.betacraft:legacyfix:nightly-7ff1a85",
			"url": "https://files.prismlauncher.org/maven"
		}
	],
	"+jvmArgs": [
		"-Dlf.deAWT=true"
	],

    "formatVersion": 1,
    "name": "Beta",
    "uid": "org.multimc.custom.beta",
    "version": "1"
}

**Comment by otroof** [comment]
> I uploaded this file in one of our own repositories, so it'll stay up forever.
> 
> Just click on the download button on the top right on this page: https://github.com/PrismLauncher/files/blob/29245eb53dc22512c944efe0916a412c7a3518a1/components/betacraft-legacyfix.json

Thanks, any idea on how to get this working with Multi mc instead of the Prism launcher?

**Comment by LeoMehraban** [comment]
I think it's the same, but i could be wrong. the buttons might be in a different place

**Comment by Scrumplex** [comment]
> Thanks, any idea on how to get this working with Multi mc instead of the Prism launcher?

I don't think MultiMC has a feature to import these json files.

But there is an alternative way to do this.

Click on `Add Empty`, add `BetaCraft LegacyFix` as the name (the first text field) and `uk.betacraft.legacyfix` as the id (second text field)

![Screenshot showing component creation dialog](https://scrumplex.rocks/img/1702549824_we8Aoz.png)

Then after that select the newly created entry and click `Edit`, which should open the file in your default text editor. Now just paste the contents from the link I posted above in that file, save the file and close the editor. Now it should be ready to go.

Edit: Obviously it would be even better, if you would use Prism Launcher as it has way better support for Minecraft on ARM64 macOS. You would be able to run the game natively, instead of having to rely on Rosetta.

**Comment by otroof** [comment]
I tried your method, doesnt seem to work on multiMC as im left with a empty screen upon launching the game. I also tried the Prism launcher where it seems to work, one weird thing is that it open another window called null where to game is shown. 

Edit, ARM64 might be the issue for multiMC. It shows and error in the log saying that it needs ARM64.

**Comment by GAM3S-TV** [comment]
> > Thanks, any idea on how to get this working with Multi mc instead of the Prism launcher?
> 
> I don't think MultiMC has a feature to import these json files.
> 
> But there is an alternative way to do this.
> 
> Click on `Add Empty`, add `BetaCraft LegacyFix` as the name (the first text field) and `uk.betacraft.legacyfix` as the id (second text field)
> 
> ![Screenshot showing component creation dialog](https://camo.githubusercontent.com/c68904a1f7471e5f833889922007840e4d878a05d3042e98881e8cb4dae55a78/68747470733a2f2f736372756d706c65782e726f636b732f696d672f313730323534393832345f776538416f7a2e706e67)
> 
> Then after that select the newly created entry and click `Edit`, which should open the file in your default text editor. Now just paste the contents from the link I posted above in that file, save the file and close the editor. Now it should be ready to go.
> 
> Edit: Obviously it would be even better, if you would use Prism Launcher as it has way better support for Minecraft on ARM64 macOS. You would be able to run the game natively, instead of having to rely on Rosetta.

After testing with this method, the game will launch with the colors but will crash the moment you press any key while also creating another weird "null" window.
This is the error I get
`Failed to add READ_ME_I_AM_VERY_IMPORTANT
Failed to add pack.mcmeta
java.io.FileNotFoundException: http://s3.amazonaws.com/MinecraftResources/
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1910)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1512)
	at java.net.URL.openStream(URL.java:1092)
	at ce.run(SourceFile:28)
java.lang.NullPointerException
	at sb.b(SourceFile:79)
	at net.minecraft.client.Minecraft.g(SourceFile:930)
	at net.minecraft.client.Minecraft.a(SourceFile:467)
	at net.minecraft.client.Minecraft.j(SourceFile:1267)
	at net.minecraft.client.Minecraft.run(SourceFile:674)
	at java.lang.Thread.run(Thread.java:750)
Stopping!`

**Comment by oofy123** [comment]
> > > Thanks, any idea on how to get this working with Multi mc instead of the Prism launcher?
> > 
> > 
> > I don't think MultiMC has a feature to import these json files.
> > But there is an alternative way to do this.
> > Click on `Add Empty`, add `BetaCraft LegacyFix` as the name (the first text field) and `uk.betacraft.legacyfix` as the id (second text field)
> > ![Screenshot showing component creation dialog](https://camo.githubusercontent.com/c68904a1f7471e5f833889922007840e4d878a05d3042e98881e8cb4dae55a78/68747470733a2f2f736372756d706c65782e726f636b732f696d672f313730323534393832345f776538416f7a2e706e67)
> > Then after that select the newly created entry and click `Edit`, which should open the file in your default text editor. Now just paste the contents from the link I posted above in that file, save the file and close the editor. Now it should be ready to go.
> > Edit: Obviously it would be even better, if you would use Prism Launcher as it has way better support for Minecraft on ARM64 macOS. You would be able to run the game natively, instead of having to rely on Rosetta.
> 
> After testing with this method, the game will launch with the colors but will crash the moment you press any key while also creating another weird "null" window. This is the error I get `Failed to add READ_ME_I_AM_VERY_IMPORTANT Failed to add pack.mcmeta java.io.FileNotFoundException: http://s3.amazonaws.com/MinecraftResources/ at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1910) at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1512) at java.net.URL.openStream(URL.java:1092) at ce.run(SourceFile:28) java.lang.NullPointerException at sb.b(SourceFile:79) at net.minecraft.client.Minecraft.g(SourceFile:930) at net.minecraft.client.Minecraft.a(SourceFile:467) at net.minecraft.client.Minecraft.j(SourceFile:1267) at net.minecraft.client.Minecraft.run(SourceFile:674) at java.lang.Thread.run(Thread.java:750) Stopping!`

mine didnt even stop, it locked up. i had to force quit it using a special menu

**Comment by DioEgizio** [comment]
> > Thanks, any idea on how to get this working with Multi mc instead of the Prism launcher?
> 
> I don't think MultiMC has a feature to import these json files.
> 
> But there is an alternative way to do this.
> 
> Click on `Add Empty`, add `BetaCraft LegacyFix` as the name (the first text field) and `uk.betacraft.legacyfix` as the id (second text field)
> 
> ![Screenshot showing component creation dialog](https://camo.githubusercontent.com/c68904a1f7471e5f833889922007840e4d878a05d3042e98881e8cb4dae55a78/68747470733a2f2f736372756d706c65782e726f636b732f696d672f313730323534393832345f776538416f7a2e706e67)
> 
> Then after that select the newly created entry and click `Edit`, which should open the file in your default text editor. Now just paste the contents from the link I posted above in that file, save the file and close the editor. Now it should be ready to go.
> 
> Edit: Obviously it would be even better, if you would use Prism Launcher as it has way better support for Minecraft on ARM64 macOS. You would be able to run the game natively, instead of having to rely on Rosetta.

multimc doesn't support agents in general

**Comment by kitsah** [comment]
The fix no longer works.

The legacyfix json file references a link called
" https://files.prismlauncher.org/maven "

which now gives a 404 error.

**Comment by DioEgizio** [comment]
> The fix no longer works.
> 
> The legacyfix json file references a link called " [files.prismlauncher.org/maven](https://files.prismlauncher.org/maven) "
> 
> which now gives a 404 error.

that's normal, just install the component

**Comment by kitsah** [comment]
> > The fix no longer works.
> 
> > 
> 
> > The legacyfix json file references a link called " [files.prismlauncher.org/maven](https://files.prismlauncher.org/maven) "
> 
> > 
> 
> > which now gives a 404 error.
> 
> 
> 
> that's normal, just install the component

My Minecraft doesn't even launch when I have the legacyfix JSON file added, some sort of 404 error is reported in console, but it doesn't crash when I remove the fix

**Comment by lxirsh** [comment]
I got it working using the method described in this video. You need to make sure to use the Java version linked in the video, otherwise you may get a white screen when going to fullscreen using ctrl + fn + f11.

https://youtu.be/Udnl4wJJojo?si=N71I3f9eAsK--fuG

And in case the video is not available in the future, here's a direct link to the correct Java version: https://www.azul.com/core-post-download/?endpoint=zulu&uuid=3646391e-f4e3-4eac-bc39-40de6ce28ffe

You need to choose version 1.8.0_372 in the launcher and after switching to full screen mode the colors should be correct.

**Comment by wilebaldo** [comment]
> I got it working using the method described in this video. You need to make sure to use the Java version linked in the video, otherwise you may get a white screen when going to fullscreen using ctrl + fn + f11.
> 
> https://youtu.be/Udnl4wJJojo?si=N71I3f9eAsK--fuG
> 
> And in case the video is not available in the future, here's a direct link to the correct Java version: https://www.azul.com/core-post-download/?endpoint=zulu&uuid=3646391e-f4e3-4eac-bc39-40de6ce28ffe
> 
> You need to choose version 1.8.0_372 in the launcher and after switching to full screen mode the colors should be correct.

Thanks, I will try this and see if this can fix the problem.

**Comment by Moresteck** [comment]
FYI, all you need to do to fix the inventory opening crash with legacyfix is to add `-Dlf.patchMouse` to JVM arguments.

**Comment by LukasMFR** [comment]
> I got it working using the method described in this video. You need to make sure to use the Java version linked in the video, otherwise you may get a white screen when going to fullscreen using ctrl + fn + f11.
> 
> https://youtu.be/Udnl4wJJojo?si=N71I3f9eAsK--fuG
> 
> And in case the video is not available in the future, here's a direct link to the correct Java version: https://www.azul.com/core-post-download/?endpoint=zulu&uuid=3646391e-f4e3-4eac-bc39-40de6ce28ffe
> 
> You need to choose version 1.8.0_372 in the launcher and after switching to full screen mode the colors should be correct.

I used this on my MacBook Pro M3 Pro and it does seem to work pretty well. I tested on a1.1.2_01 and I used Prism, I only chose the right Java version and did not have to install anything else, I just had to make sure to put the game in full screen mode to get get the right colors.

**Comment by MisterSheeple** [comment]
> Having just dived through the code i think im mistaken on legacyfix, though im not entirely sure what it’s actually doing yet.

I'm told by the developer of legacyfix that their fix for this involves running the game inside a LWJGL frame instead of an applet. He says the only drawback to this is that the game sometimes crashes when resizing the window on ARM Macs, but I don't think Prism Launcher currently supports that on legacy versions anyway, so that shouldn't be a problem.

**Comment by Lassebq** [comment]
There's also https://github.com/MCPHackers/LaunchWrapper.
While I haven't seen people complain about resizing frame causing crashes, there weren't that many mac users who tested it to begin with. If you're a mac user and you use prism launcher please let me know.

**Comment by Lassebq** [comment]
> > Having just dived through the code i think im mistaken on legacyfix, though im not entirely sure what it’s actually doing yet.
> 
> I'm told by the developer of legacyfix that their fix for this involves running the game inside a LWJGL frame instead of an applet. He says the only drawback to this is that the game sometimes crashes when resizing the window on ARM Macs, but I don't think Prism Launcher currently supports that on legacy versions anyway, so that shouldn't be a problem.

But yes applet/AWT canvas is a single destructive thing which causes issues, not only on mac, but on linux too. Especially with mouse input in versions before a1.0.1_01. Getting rid of it in favor of LWJGL frame is the way to go
