### ISSUE TITLE
Mac M1, can't load server resource pack

### ISSUE THREAD

**Issue by billsboard** [PrismLauncher/PrismLauncher#935]
### Version of Prism Launcher

Prism launcher 6.3

### Version of Qt

Qt 6.3.0

### Description of bug

Logging onto any server with  and attempting to download the server-side resource pack when the prompt pops up will cause the download to get stuck at "Making request: 100%" and never complete the download.

### Steps to reproduce

- Create MC instance
- Go to a server with a resource pack prompt
- Download the pack
- MC will hang at "Making request: 100%"

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ghost** [comment]
Create a `server-resource-packs` folder in `.minecraft`

**Comment by billsboard** [comment]
> Create a `server-resource-packs` folder in `.minecraft`

I do have such a folder. Tried deleting it, recreating it, but it still doesn't work

**Comment by billsboard** [comment]
The console error log is:

```
[10:08:51] [Downloader 0/ERROR]: Failed to download file
java.net.SocketException: Operation timed out
	at sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:325) ~[?:?]
	at sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350) ~[?:?]
	at sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803) ~[?:?]
	at java.net.Socket$SocketInputStream.read(Socket.java:966) ~[?:?]
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:244) ~[?:?]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284) ~[?:?]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:343) ~[?:?]
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:791) ~[?:?]
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:726) ~[?:?]
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:750) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1688) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?]
	at net.minecraft.class_3521.method_15303(class_3521.java:63) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]	
```

I can guarantee the resource pack site is working and my connection is fine. This occurs on any server and also on any version

**Comment by MikeRBLX** [comment]
I'm having the same issue here after installing the launcher. It works fine in Minecraft Launcher. I did create a server resource pack in .minecraft, joined and didn't work. Quitted and placed that texture pack in the folder, rejoined and still not working.

**Comment by omrih4** [comment]
same here on linux.
